bar.art.create('Recomendado');
bar.art.create('A', [
  bar.music.create('4 Dance', 'MODO DE SER'),
  bar.music.create('Academia de estrelas', 'Alma na voz'),
  bar.music.create('Accioly Neto', 'Minha Gata'),
  bar.music.create('Adelaide Ferreira', 'Alma vazia'),
  bar.music.create('Adelaide Ferreira', 'Dá-me o teu amor'),
  bar.music.create('Adelaide Ferreira', 'DOU-TE O MUNDO'),
  bar.music.create('Adelaide Ferreira', 'EU DAVA TUDO'),
  bar.music.create('Adelaide Ferreira', 'PARA O QUE DER E VIER'),
  bar.music.create('Adelaide Ferreira', 'Papel principal'),
  bar.music.create('Adelaide Ferreira', 'VEM NO MEU SONHO'),
  bar.music.create('Adelaide Ferreira', 'Vem no meu sonho'),
  bar.music.create('Adelaide e Dulce (dueto)', 'Papel principal'),
  bar.music.create('Adiafa', 'A mula da cooperativa'),
  bar.music.create('Adiafa', 'AS MENINAS DA RIB. DO SADO'),
  bar.music.create('Adiafa', 'AS MENINAS DO SADO(Dance)'),
  bar.music.create('Adoniran Barbosa', 'Trem das onze'),
  bar.music.create('Adriana Calcanhoto', 'Fico assim sem você'),
  // bar.music.create('Aerosmith', 'I Don\'t Wanna Miss a Thing', 'aerosmith-i-dont-wanna-miss-a-thing.mp4'),
  bar.music.create('Aerosmith', 'I Don\'t Wanna Miss a Thing', 'aerosmith-i-dont-wanna-miss-a-thing-low.mp4'),
  // bar.music.create('Aerosmith', 'I Don\'t Wanna Miss a Thing'),
  bar.music.create('Afonsinho do Condado', 'A salsa das Amoreiras'),
  bar.music.create('Afonsinho do contudo', 'Rola no chão'),
  bar.music.create('Ágata & Romana', 'De mulher para mulher'),
  bar.music.create('Ágata', 'Comunhão de Bens'),
  bar.music.create('Ágata', 'Coração que ama (coração apaixonado)'),
  bar.music.create('Ágata', 'MÃE SOLTEIRA'),
  bar.music.create('Ágata', 'Maldito amor'),
  bar.music.create('Ágata', 'Perfume de Mulher'),
  bar.music.create('Além Mar', 'Já não há mais baladas'),
  bar.music.create('Além mar', 'Deixa-me olhar'),
  bar.music.create('Ala dos Namorados', 'CAÇADOR DE SÓIS'),
  bar.music.create('Ala dos Namorados', 'O FIM DO MUNDO'),
  bar.music.create('Ala dos Namorados', 'O Fim do mundo'),
  bar.music.create('Ala dos Namorados', 'Os loucos de Lisboa'),
  bar.music.create('Ala dos Namorados', 'SOLTA-SE O BEIJO'),
  bar.music.create('Alcoolémia', 'Não sei se mereço'),
  bar.music.create('Alex', 'Mister gay'),
  bar.music.create('Alexandra', 'Zé brasileiro português de braga'),
  bar.music.create('Alexandra', 'Zé brasileiro'),
  bar.music.create('Alexandre boris', 'Bem ou mal'),
  bar.music.create('Alexandre Pires', 'É por amor'),
  bar.music.create('Alexandre Pires', 'Necessidade'),
  bar.music.create('Alexandre Pires', 'Sem teu amor'),
  bar.music.create('Alexandre Pires', 'Você roubou a minha vida'),
  bar.music.create('Amarginhas', 'Just girl´s'),
  bar.music.create('Ana Malhoa', 'BANHO DE LUA'),
  bar.music.create('Ana Malhoa', 'Eu sou latina'),
  bar.music.create('Ana Malhoa', 'Nada me pará'),
  bar.music.create('Ana Malhoa', 'Por amor'),
  bar.music.create('Ana Malhoa', 'TEU CORPO ARDENTE'),
  bar.music.create('Anabela', 'A cidade (ate ser dia)'),
  bar.music.create('Anabela', 'Cidade até ser dia'),
  bar.music.create('Anabela', 'estou aqui'),
  bar.music.create('André Sardet & Mafalda Veiga', 'Hoje vou ficar'),
  bar.music.create('André Sardet', 'Azul do céu'),
  bar.music.create('André Sardet', 'Azul do céu'),
  bar.music.create('André Sardet', 'Foi Feitiço'),
  bar.music.create('André Sardet', 'QUANDO EU TE FALEI DE AMOR'),
  bar.music.create('Anjos', 'A VIDA FAZ-ME BEM'),
  bar.music.create('Anjos', 'Bem longe num sonho teu'),
  bar.music.create('Anjos', 'Como um anjo'),
  bar.music.create('Anjos', 'EU ESTOU AQUI (EU SOU AQUELE)'),
  bar.music.create('Anjos', 'Ficarei'),
  bar.music.create('Anjos', 'PERDOA'),
  bar.music.create('Anjos', 'PORQUÊ ( NUNCA MAS )'),
  bar.music.create('Anjos', 'Quando fores grande'),
  bar.music.create('Anjos', 'Quero voltar'),
  bar.music.create('Anjos', 'SEI QUE VOU MAIS ALÉM'),
  bar.music.create('Anjos', 'Sei que vou mais além'),
  bar.music.create('Anjos', 'Sou como o vento'),
  bar.music.create('Anjos', 'TUDO É UM SONHO'),
  bar.music.create('Anjos', 'Tudo é um sonho'),
  bar.music.create('António Calvário', 'É P\'RA AMANHÃ'),
  bar.music.create('António Calvário', 'Ó tempo volta para trás'),
  bar.music.create('António Calvário', 'Canção de engate'),
  bar.music.create('António Calvário', 'Estou além'),
  bar.music.create('António Calvário', 'Homem de Nazaré'),
  bar.music.create('António Calvário', 'MOCIDADE, MOCIDADE'),
  bar.music.create('António Calvário', 'Oração'),
  bar.music.create('António Mafra', 'Baile da D. Ester'),
  bar.music.create('António Variações', 'O corpo é que paga'),
  bar.music.create('Araketu', 'Mal acostumado'),
  bar.music.create('Aramac', 'MÁGOA DE SAL'),
  bar.music.create('Armando Gama', 'BALADA QUE TE DOU'),
  bar.music.create('Armando Gama', 'Esta balada'),
  bar.music.create('Armando Louzada', 'Fascinaçao'),
  bar.music.create('Augusto César', 'AGUENTA CORAÇÃO'),
  bar.music.create('Avô Cantigas', 'FANTASMINHA BRINCALHÃO'),
  bar.music.create('Aventura', 'OBSESIÓN'),
  bar.music.create('Axel', 'COMO É QUE EU SEI')
]);
bar.art.create('B', [
  bar.music.create('Banda Brasil', 'O TUBARÃO'),
  bar.music.create('Banda Calypso', 'CUMBIA DO AMOR'),
  bar.music.create('Banda Calypso', 'CHICLETE COM CALYPSO'),
  bar.music.create('Banda Eva', 'Vem meu amor'),
  bar.music.create('Banda Eva', 'Levada louca'),
  bar.music.create('Banda Eva', 'LEVADA LOUCA'),
  bar.music.create('Banda Eva', 'Arere'),
  bar.music.create('Banda Eva', 'Beleza Rara'),
  bar.music.create('Banda Íris', 'ATIRA TÓ MAR'),
  bar.music.create('Bandalusa', 'YE, YE, YE PRIMEIRO AMOR'),
  bar.music.create('Bandalusa', 'MORENA AI AI'),
  bar.music.create('Bandalusa', 'ESTOU TONTO DE SAUDADE'),
  bar.music.create('Bandalusa', 'Ye, ye, ye'),
  bar.music.create('Bandalusa', 'Bate, Bate, Bate'),
  bar.music.create('Bandalusa', 'Rainha das tentações'),
  bar.music.create('Beatriz Costa', 'A AGULHA E O DEDAL'),
  bar.music.create('Bel Viana', 'I WANNA MAKE IT ALL RIGHT'),
  bar.music.create('Benito Di Paula', 'Charlie Brown'),
  bar.music.create('Benito Di Paula', 'Retalho de Cetim'),
  bar.music.create('Beth Carvalho', 'Andanças'),
  bar.music.create('Beto', 'FUGIR DOS MEUS MEDOS'),
  bar.music.create('Beto & Rita Guerra', 'Brincando com o fogo'),
  bar.music.create('Beto & Rita Guerra', 'Desencontros'),
  bar.music.create('Beto', 'Dois corações unidos a cantar'),
  bar.music.create('Beto', 'Tudo por amor'),
  bar.music.create('Beto', 'Dois corações unidos'),
  bar.music.create('Beto', 'Memórias esquecidas'),
  bar.music.create('Bombocas', 'Já os topamos'),
  bar.music.create('Bonga', 'MARIQUINHA'),
  bar.music.create('Bonga', 'CURRUMBA'),
  bar.music.create('Bonga', 'Olhos molhados'),
  bar.music.create('Boss ac', 'Boa vibe'),
  bar.music.create('Boss AC', 'HIP HOP (sou eu e és tu)'),
  bar.music.create('Brasileira', 'amarelinha'),
  bar.music.create('Brasileira', 'spc'),
  bar.music.create('Brasileira', 'sentimento nu'),
  bar.music.create('Brasileira', 'e tar de de mais'),
  bar.music.create('Brasileira', 'beijo geladinho'),
  bar.music.create('Brasileira', 'faixa amarela'),
  bar.music.create('Brasileira', 'maneirinho'),
  bar.music.create('Brasileira', 'La vem o négao'),
  bar.music.create('Brasileira', 'sai da minha aba'),
  bar.music.create('Brasileira', 'no mexe , no bole'),
  bar.music.create('Broa de Mel', 'Passear contigo'),
  bar.music.create('Bruno & marrone', 'Dormir na praça'),
  bar.music.create('Bruno & marrone', 'Bijutaria'),
  bar.music.create('Bruno & Marrone', 'Quer casar comigo')
]);
bar.art.create('C', [
  bar.music.create('Cabeça no ar', 'O meu primeiro beijo'),
  bar.music.create('Cabeça no ar', 'A seita tem um radar'),
  bar.music.create('Cabeças no Ar', 'Jesus no secundário'),
  bar.music.create('Cabeças no Ar', 'A corrente do jogo'),
  bar.music.create('Caetano Veloso', 'Sozinho'),
  bar.music.create('Caetano Veloso', 'Alegria, alegria'),
  bar.music.create('Caetano Veloso', 'Menino do rio'),
  bar.music.create('Caetano Veloso', 'Como 2 e 2'),
  bar.music.create('Cândida Branca Flor', 'Maria Papoila'),
  bar.music.create('Canta Bahia', 'Morango do Nordeste'),
  bar.music.create('Canta Bahia', 'Ilarie'),
  bar.music.create('Canta Bahia', 'Paixão e loucura'),
  bar.music.create('Canta Bahia', 'ILA RIÊ'),
  bar.music.create('Canta Bahia', 'PAIXÃO E LOUCURA'),
  bar.music.create('Canta Bahia', 'FESTANÇA'),
  bar.music.create('Canta Bahia', 'CARLA'),
  bar.music.create('Carlos Alexandre', 'Verde vinho'),
  bar.music.create('Carlos do Carmo', 'Estrela da tarde'),
  bar.music.create('Carlos do Carmo', 'FLOR DE VERDE PINHO'),
  bar.music.create('Carlos do Carmo', 'Um homem na cidade'),
  bar.music.create('Carlos Guilherme', 'ADEUS'),
  bar.music.create('Carlos Guilherme', 'Quando o coração chora'),
  bar.music.create('Carlos Mendes', 'Amélia dos olhos doces'),
  bar.music.create('Carlos Mendes', 'Festa da vida'),
  bar.music.create('Carlos Paião & Dina', 'QUANDO AS NUVENS CHORAREM'),
  bar.music.create('Carlos Paião', 'Playback'),
  bar.music.create('Carlos Paião', 'Cinderela'),
  bar.music.create('Carlos Paião', 'Pó de arroz'),
  bar.music.create('Carlos Paião', 'CINDERELA'),
  bar.music.create('Carlos Paião', 'PÓ DE ARROZ'),
  bar.music.create('Carlos Paião', 'MARCHA DO "PIÃO DAS NICAS"'),
  bar.music.create('Carlos Paião', 'Cinderela'),
  bar.music.create('Carlos Paião', 'Versos de amor'),
  bar.music.create('Carlos Paião', 'GA-GAGO'),
  bar.music.create('Carlos Paião', 'play-back'),
  bar.music.create('Cármen Miranda', 'Que é que a Baiana tem'),
  bar.music.create('Cármen Miranda', 'Adeus solidão'),
  bar.music.create('Cazuza', 'O nosso amor a gente inventa (Estória Romântica)'),
  bar.music.create('cazuza/ renato ladeira', 'faz parte do meu show'),
  bar.music.create('ceceu', 'bate coraçao'),
  bar.music.create('Cesária Évora', 'SODADE'),
  bar.music.create('Chayanne', 'TORERO'),
  bar.music.create('Cheiro de Amor', 'Vai sacudir, vai abalar'),
  bar.music.create('Chico Buarque', 'Carolina'),
  bar.music.create('Chico Buarque', 'Apesar de você'),
  bar.music.create('Chico Buarque', 'Quem te viu, quem te vê'),
  bar.music.create('Chico Buarque', 'Valsinha'),
  bar.music.create('Chiquita', 'Os homens …+bonitos'),
  bar.music.create('Chiquita', 'Balde de agua fria'),
  bar.music.create('Clã', 'COMPETÊNCIA PARA AMAR'),
  bar.music.create('Clã', 'Problema de expressão'),
  bar.music.create('Cláudia Isabel', 'Preciso de um herói'),
  bar.music.create('Cláudia', 'Não posso de ti fugir'),
  bar.music.create('Claudia Isabel', 'ROSINHA DOS LIMÕES'),
  bar.music.create('Conjunto António Mafra', 'Sete e pico')
]);
bar.art.create('D', [
  bar.music.create('D\'arrasar', 'Rainha da noite'),
  bar.music.create('Da vinci', 'Conquistador'),
  bar.music.create('Da Weasel', 'Tas na boa'),
  bar.music.create('Da Weasel', 'Restritamente'),
  bar.music.create('Da Weasel', 'CASA(VEM FAZER DE CONTA)'),
  bar.music.create('Da Weasel', 'DIALECTOS DE TERNURA'),
  bar.music.create('Da Weasel', 'CASA (vem fazer de conta'),
  bar.music.create('Da Weasel', 'FORÇA'),
  bar.music.create('Da Weasel', 'Re-tratamento'),
  bar.music.create('Da Weasel', 'Casa (vem fazer de conta)'),
  bar.music.create('Daniela Mercury', 'O canto da cidade'),
  bar.music.create('Daniela Mercury', 'Swing da côr'),
  bar.music.create('Daniela Mercury', 'Nobre vagabundo'),
  bar.music.create('David Fonseca', 'Someone that cannot love'),
  bar.music.create('David Fonseca', 'THE 80\'S'),
  bar.music.create('David Fonseca', 'Who are you'),
  bar.music.create('Delfins', 'A cor azul'),
  bar.music.create('Delfins', 'Canção do engate'),
  bar.music.create('Delfins', 'A cor azul'),
  bar.music.create('Delfins', 'Babilónia'),
  bar.music.create('Delfins', 'E preciso'),
  bar.music.create('Delfins', 'Num sonho teu'),
  bar.music.create('Delfins', 'Sou como um rio'),
  bar.music.create('Delfins', 'Saber amar'),
  bar.music.create('Delfins', 'A Queda de um anjo'),
  bar.music.create('Delfins', 'Vive ( tema do Big Brother )'),
  bar.music.create('Delfins', 'Não vou ficar'),
  bar.music.create('Delfins', 'Ao passar de um navio'),
  bar.music.create('Delfins', 'Saber amar'),
  bar.music.create('Delfins', 'Aquele Inverno'),
  bar.music.create('Delfins', 'Babilónia'),
  bar.music.create('Delfins', 'É preciso'),
  bar.music.create('Delfins', 'Baía de Cascais'),
  bar.music.create('Delfins', 'Sou como um rio'),
  bar.music.create('Demétrius', 'O Ritmo da Chuva'),
  bar.music.create('Despe & Siga', 'Manual de Gelo'),
  bar.music.create('Despe & Siga', 'Bule das baldas'),
  bar.music.create('Despe & Siga', 'Manual do gelo'),
  bar.music.create('Despe & Siga', 'Rádio ska'),
  bar.music.create('Despe & Siga', 'Sol da Caparica'),
  bar.music.create('Despe & Siga', 'FESTA'),
  bar.music.create('Diana Basto', 'GRITA SENTE'),
  bar.music.create('Diana Basto', 'LIBERDADE'),
  bar.music.create('Diapasão', 'Era pouco e acabou-se'),
  bar.music.create('Diapasão', 'Canção da Maria'),
  bar.music.create('Diapasão', 'Mentiras'),
  bar.music.create('Diapasão', 'Cigana, cigana linda'),
  bar.music.create('Diapasão', 'Festa dos insectos'),
  bar.music.create('Diapasão', 'MENTIRAS, MENTIRAS'),
  bar.music.create('Diapasão', 'CIGANA, CIGANA LINDA'),
  bar.music.create('Diapasão', 'FESTA DOS INSECTOS'),
  bar.music.create('Diapasão', 'GARÇON'),
  bar.music.create('Diapasão', 'EU VOU AMÁ-LA'),
  bar.music.create('Diapasão', 'BELA PORTUGUESA'),
  bar.music.create('Diapasão', 'VIAGEM POSTAL'),
  bar.music.create('Diapasão', 'VAI SOBRAR MULHER'),
  bar.music.create('Diapasão', 'CANÇÃO DA MARIA'),
  bar.music.create('Diapasão', 'HÁ FESTA FESTA NA ALDEIA'),
  bar.music.create('Diapasão', 'OLÁ TRANSMONTANA'),
  bar.music.create('Diapasão', 'Vai sobrar mulher'),
  bar.music.create('Diapasão', 'MULHER CHORONA'),
  bar.music.create('Dina', 'Amor de água fresca'),
  bar.music.create('Dina', 'VOAR OUTRA VEZ'),
  bar.music.create('Dina', 'Há sempre música entre nós'),
  bar.music.create('Dina', 'Que é de ti (Filha do mar)'),
  bar.music.create('Dino Meira', 'Meu querido mês de Agosto'),
  bar.music.create('Dino Meira', 'SEI QUE VAIS VOLTAR'),
  bar.music.create('Dino Meira', 'Helena'),
  bar.music.create('djavan', 'eu te devoro'),
  bar.music.create('djavan', 'oceano'),
  bar.music.create('Doce', 'Bem bom'),
  bar.music.create('Doce', 'Amanha de manha'),
  bar.music.create('Doce', 'Ali baba'),
  bar.music.create('Dolores Duran', 'A Noite do Meu Bem'),
  bar.music.create('dominguinhos / nando cordel', 'gostoso demais'),
  bar.music.create('Dora', 'Não sejas mau para mim'),
  bar.music.create('Dulce Pontes', 'Canção do mar'),
  bar.music.create('Dulce Pontes', 'Lusitana paixão'),
  bar.music.create('Dulce Pontes', 'Os índios da meia-praia'),
  bar.music.create('Dulce Pontes', 'Barco negro'),
  bar.music.create('Dulce Pontes', 'Lágrima'),
  bar.music.create('Dulce Pontes', 'Fado Português'),
  bar.music.create('Dulce Pontes', 'Canção do mar'),
  bar.music.create('Dulce Pontes', 'No teu poema'),
  bar.music.create('Dulce Pontes', 'Os índios da meia praia'),
  bar.music.create('Dulce Pontes', 'Povo que lavas no rio'),
  bar.music.create('Dulce Pontes', 'Lágrima'),
  bar.music.create('Dulce Pontes', 'Que amor não me engana'),
  bar.music.create('Dulce Pontes', 'Estranha forma de vida'),
  bar.music.create('Dulce Pontes', 'Barco abandonado'),
  bar.music.create('Dulce Pontes', 'VERDES ANOS'),
  bar.music.create('Dulce Pontes', 'FILHO AZUL'),
  bar.music.create('Dulce Pontes', 'Povo que lavas no rio'),
  bar.music.create('Dulce Pontes', 'ÍNDIOS DA MEIA PRAIA'),
  bar.music.create('Dulce Pontes', 'FADO PORTUGUÊS'),
  bar.music.create('Dulce Pontes', 'CANÇÃO DO MAR'),
  bar.music.create('Dulce Pontes', 'NOVO FADO DA SEVERA'),
  bar.music.create('Dulce Pontes', 'Fado português'),
  bar.music.create('Dulce Pontes', 'Lusitana paixão'),
  bar.music.create('Duo Ouro Negro', 'Vou levar-te comigo'),
  bar.music.create('Duo Ouro Negro', 'MARIA RITA'),
  bar.music.create('D\'ZRT', 'PARA MIM TANTO FAZ')
]);
bar.art.create('E', [
  bar.music.create('Eduardo Nascimento', 'O vento mudou'),
  bar.music.create('El símbolo', 'Nunca te decides'),
  bar.music.create('El símbolo', 'Levantando lás manos'),
  bar.music.create('Elba Ramalho', 'Chuva de Prata'),
  bar.music.create('Elba Ramalho', 'De volta p\'ro aconchego'),
  bar.music.create('Elis Regina', 'Como Nossos Pais'),
  bar.music.create('Elis Regina', 'O Bêbado e o Equilibrista'),
  bar.music.create('Elis Regina', 'Maria Maria'),
  bar.music.create('Emanuel', 'Pimba'),
  bar.music.create('Emanuel', 'Vamos a elas'),
  bar.music.create('Emanuel', 'Vamos ao céu'),
  bar.music.create('Emanuel', 'Ó SENHOR GUARDA'),
  bar.music.create('Emanuel', 'QUEM ME ACODE'),
  bar.music.create('Emanuel', 'BRINCA COMIGO MARIA'),
  bar.music.create('Emanuel', 'É O PIRIPIRI'),
  bar.music.create('Emanuel', 'VAMOS AO BAILE'),
  bar.music.create('Emanuel', 'QUE GRANDE BRONCA'),
  bar.music.create('Emanuel', 'FELICIDADE (quando o telefone toca)'),
  bar.music.create('Emanuel', 'Ó Sr. Guarda (não leve a mal)'),
  bar.music.create('Emanuel', 'Minha querida noiva'),
  bar.music.create('Emanuel', 'Pimba Pimba'),
  bar.music.create('Emanuel', 'Brinca comigo Maria'),
  bar.music.create('Emanuel', 'Vamos ao baile (vamos)'),
  bar.music.create('Ena pá 2000', 'És cruel'),
  bar.music.create('Entre asas', 'Uma pequena flor'),
  bar.music.create('Entre aspas', 'Criatura da noite'),
  bar.music.create('érgio Godinho', 'Com um brilhozinho nos olhos'),
  bar.music.create('Excesso', 'TUDO MUDOU'),
  bar.music.create('Excesso', 'Eu sou aquele'),
  bar.music.create('Excesso', 'Não sei viver sem ti'),
  bar.music.create('Excesso', 'Eu sou aquele'),
  bar.music.create('Ez Special', 'MENINA BONITA')
]);
bar.art.create('F', [
  bar.music.create('Fado', 'O embuçado'),
  bar.music.create('Fado', 'Lisboa antiga'),
  bar.music.create('Fado', 'Lisboa à noite'),
  bar.music.create('Fado', 'Barco Negro'),
  bar.music.create('Fado', 'Fado do estudante'),
  bar.music.create('Fado', 'Por morrer uma andorinha'),
  bar.music.create('Fado', 'Fado da Sina'),
  bar.music.create('Fado', 'AMAR'),
  bar.music.create('Fado', 'VOU DAR DE BEBER À DOR'),
  bar.music.create('Fado', 'PROCURO E NÃO TE ENCONTRO'),
  bar.music.create('Fado', 'TUDO ISTO É FADO'),
  bar.music.create('Fado', 'A Rosinha dos limões'),
  bar.music.create('Fado', 'Fado do 31'),
  bar.music.create('Fado', 'Duas lágrimas de orvalho'),
  bar.music.create('Fado', 'A moda das tranças pretas'),
  bar.music.create('Fado', 'Lisboa menina e moça'),
  bar.music.create('Fado', 'Gaivota'),
  bar.music.create('Fado', 'NOVO FADO DA SEVERA'),
  bar.music.create('Fado', 'HÁ FESTA NA MOURARIA'),
  bar.music.create('Fado', 'LUGAR VAZIO'),
  bar.music.create('Fado', 'Não venhas tarde'),
  bar.music.create('Fado', 'Os putos'),
  bar.music.create('Fado', 'O homem das castanhas'),
  bar.music.create('Fado', 'Engatatão das dúzias'),
  bar.music.create('Fado', 'Cavalo Ruço'),
  bar.music.create('Fado', 'Foi Deus'),
  bar.music.create('Fado', 'É ou não é'),
  bar.music.create('Fado', 'Canoas do Tejo'),
  bar.music.create('Fado', 'Lenda da fonte'),
  bar.music.create('Fado', 'Ai mouraria'),
  bar.music.create('Fado', 'Os meninos de Huambo'),
  bar.music.create('Fado', 'Bairro alto'),
  bar.music.create('Fado', 'Igreja de Santo Estevão'),
  bar.music.create('Fado', 'Fado dos cheirinhos'),
  bar.music.create('Fado', 'Fado do Marialva'),
  bar.music.create('Fado', 'Aquela janela virada p\'ro mar'),
  bar.music.create('Fado', 'Uma casa portuguesa'),
  bar.music.create('Fado', 'Zé cacilheiro'),
  bar.music.create('Fado de Coimbra', 'O FADO DOS PASSARINHOS'),
  bar.music.create('Fado de Coimbra', 'O MEU MENINO'),
  bar.music.create('Fado de Coimbra', 'BALADA DA DESPEDIDA'),
  bar.music.create('Fado de Coimbra', 'CONTOS VELHINHOS'),
  bar.music.create('Fado de Coimbra', 'COIMBRA MENINA E MOÇA'),
  bar.music.create('Fado de Coimbra', 'SAMARITANA'),
  bar.music.create('Fado de Coimbra', 'BALADA PARA UMA VELHINHA'),
  bar.music.create('Fado de Coimbra', 'TRAZ OUTRO AMIGO TAMBÉM'),
  bar.music.create('Fado de Coimbra', 'SAUDADES DE COIMBRA'),
  bar.music.create('Fado de Coimbra', 'TROVA DO VENTO QUE PASSA'),
  bar.music.create('Fado de Lisboa', 'MENINA DAS TRANÇAS PRETAS'),
  bar.music.create('Fado de Lisboa', 'TUDO ISTO É FADO'),
  bar.music.create('Fado de Lisboa', 'LISBOA À NOITE'),
  bar.music.create('Fado de Lisboa', 'RUA DO CAPELÃO'),
  bar.music.create('Fado de Lisboa', 'SEMPRE QUE LISBOA CANTA'),
  bar.music.create('Fado de Lisboa', 'POVO QUE LAVAS NO RIO'),
  bar.music.create('Fado de Lisboa', 'POR MORRER UMA ANDORINHA'),
  bar.music.create('Fado de Lisboa', 'OS PUTOS'),
  bar.music.create('Fado de Lisboa', 'OLHOS CASTANHOS'),
  bar.music.create('Fado de Lisboa', 'NÃO VENHAS TARDE'),
  bar.music.create('Fado de Lisboa', 'O AMOR É LOUCO'),
  bar.music.create('Fado de Lisboa', 'NEM ÀS PAREDES CONFESSO'),
  bar.music.create('Fado de Lisboa', 'O HOMEM DAS CASTANHAS'),
  bar.music.create('Fado de Lisboa', 'LISBOA MENINA E MOÇA'),
  bar.music.create('Fado de Lisboa', 'FADO FADISTA'),
  bar.music.create('Fado de Lisboa', 'FADO ESTUDANTE'),
  bar.music.create('Fado de Lisboa', 'Ó GENTE DA MINHA TERRA'),
  bar.music.create('Fado de Lisboa', 'SÓ NÓS DOIS'),
  bar.music.create('Fado de Lisboa', 'LÁGRIMA'),
  bar.music.create('Fado de Lisboa', 'O COCHICHO'),
  bar.music.create('Fado de Lisboa', 'Ó TEMPO VOLTA P’RA TRÁS'),
  bar.music.create('Fado de Lisboa', 'OS MENINOS DO HUAMBO'),
  bar.music.create('Fado de Lisboa', 'FADINHO DA TI MARIA BENTA'),
  bar.music.create('Fado de Lisboa', 'FADO DA GARGANTILHA'),
  bar.music.create('Fado de Lisboa', 'NOITE'),
  bar.music.create('Fado de Lisboa', 'MORENA AÍ DO CANTO'),
  bar.music.create('Fado de Lisboa', 'ATÉ O REI IA AO FADO'),
  bar.music.create('Fado de Lisboa', 'MARIA LISBOA'),
  bar.music.create('Fado de Lisboa', 'ROSEIRA BOTÃO DE GENTE'),
  bar.music.create('Fado de Lisboa', 'Ó CARECA'),
  bar.music.create('Fado de Lisboa', 'O XAILE DE MINHA MÃE'),
  bar.music.create('Fado de Lisboa', 'NAMORICO DA RITA'),
  bar.music.create('Fado de Lisboa', 'OIÇA LÁ Ó SENHOR VINHO'),
  bar.music.create('Fado de Lisboa', 'LUGAR VAZIO'),
  bar.music.create('Fado de Lisboa', 'AI MOURARIA'),
  bar.music.create('Fado de Lisboa', 'LISBOA NÃO SEJAS FRANCESA'),
  bar.music.create('Fado de Lisboa', 'CAIS DO SODRÉ'),
  bar.music.create('Fado de Lisboa', 'UMA CASA PORTUGUESA'),
  bar.music.create('Fado de Lisboa', 'CANTIGAS DA RUA'),
  bar.music.create('Fado de Lisboa', 'CHUVA ( MARIZA )'),
  bar.music.create('Fado de Lisboa', 'ETERNA AMIZADE'),
  bar.music.create('Fado de Lisboa', 'FADINHO SERRANO'),
  bar.music.create('Fado de Lisboa', 'FADO DO CIÚME'),
  bar.music.create('Fado de Lisboa', 'FOI DEUS'),
  bar.music.create('Fado de Lisboa', 'GUITARRA TOCA BAIXINHO'),
  bar.music.create('Fado de Lisboa', 'LENDA DAS ROSAS'),
  bar.music.create('Fado de Lisboa', 'AMÁLIA'),
  bar.music.create('Fado de Lisboa', 'O MEU PRIMEIRO AMOR'),
  bar.music.create('Fado de Lisboa', 'FADO DAS TAMANQUINHAS'),
  bar.music.create('Fado de Lisboa', 'PODE SER MENTIRA'),
  bar.music.create('Fado de Lisboa', 'FEITICEIRA'),
  bar.music.create('Fado de Lisboa', 'TERNURA DOS QUARENTA'),
  bar.music.create('Fado de Lisboa', 'CAVALO RUÇO'),
  bar.music.create('Fado de Lisboa', 'CHEIRA A LISBOA'),
  bar.music.create('Fado de Lisboa', 'CANOAS DO TEJO'),
  bar.music.create('Fado de Lisboa', 'AQUELA JAN.VIRADA PRO MAR'),
  bar.music.create('Fado de Lisboa', 'HAVELOS DE IR A VIANA'),
  bar.music.create('Fado de Lisboa', 'MARCHA DE ALFAMA'),
  bar.music.create('Fado de Lisboa', 'LENDA DA FONTE'),
  bar.music.create('Fado de Lisboa', 'BARCO NEGRO'),
  bar.music.create('Fado de Lisboa', 'DUAS LÁGRIMAS DE ORVALHO'),
  bar.music.create('Fado de Lisboa', 'QUE DEUS ME PERDOE'),
  bar.music.create('Fado de Lisboa', 'VALEU A PENA'),
  bar.music.create('Fado de Lisboa', 'BOA NOITE SOLIDÃO'),
  bar.music.create('Fado de Lisboa', 'CANTO O FADO'),
  bar.music.create('Fado de Lisboa', 'CARMENCITA'),
  bar.music.create('Fado de Lisboa', 'O EMBUÇADO'),
  bar.music.create('Fado de Lisboa', 'É TÃO BOM SER PEQUENINO'),
  bar.music.create('Fado de Lisboa', 'FADO DO TRINTA E UM'),
  bar.music.create('Fado de Lisboa', 'TRIGUEIRINHA'),
  bar.music.create('Fado de Lisboa', 'BAIRRO ALTO'),
  bar.music.create('Fado de Lisboa', 'ESTRANHA FORMA DE VIDA'),
  bar.music.create('Fado de Lisboa', 'LISBOA ANTIGA'),
  bar.music.create('Fado de Lisboa', 'Ó PORTELA'),
  bar.music.create('Fado de Lisboa', 'CANÇÃO DE LISBOA'),
  bar.music.create('Fado de Lisboa', 'TRISTE SINA'),
  bar.music.create('Fado de Lisboa', 'VISEU SENHORA DA BEIRA'),
  bar.music.create('Fado de Lisboa', 'ATÉ QUE A VOZ ME DOA'),
  bar.music.create('Fado de Lisboa', 'BOCAS DO FADO'),
  bar.music.create('Fado de Lisboa', 'CONFESSO'),
  bar.music.create('Fado de Lisboa', 'FADO DE CADA UM'),
  bar.music.create('Fado de Lisboa', 'FADO ERRADO'),
  bar.music.create('Fado de Lisboa', 'FADO MALHOA'),
  bar.music.create('Fado de Lisboa', 'ZANGUEI-ME COM O MEU AMOR'),
  bar.music.create('Fado de Lisboa', 'BOA NOVA'),
  bar.music.create('Fado de Lisboa', 'VELHO FRIAGEM'),
  bar.music.create('Fado de Lisboa', 'SAUDADES PEREGRINAS'),
  bar.music.create('Fado de Lisboa', 'O ESPAÇO E O TEMPO'),
  bar.music.create('Fado de Lisboa', 'MARGARIDA VAI À FONTE'),
  bar.music.create('Fado de Lisboa', 'SE AO MENOS HOUVESSE UM DIA'),
  bar.music.create('Fado de Lisboa', 'VIELAS DE ALFAMA'),
  bar.music.create('Fado de Lisboa', 'ADEUS MOURARIA'),
  bar.music.create('Fado de Lisboa', 'TREM DESMANTELADO'),
  bar.music.create('Fado de Lisboa', 'ESMERALDINHA'),
  bar.music.create('Fado de Lisboa', 'MARIA MADALENA'),
  bar.music.create('Fado de Lisboa', 'FADO CRAVO'),
  bar.music.create('Fado de Lisboa', 'FADO BACALHAU'),
  bar.music.create('Fado de Lisboa', 'FEIRA DA LADRA'),
  bar.music.create('Fado de Lisboa', 'FADO SAGITÁRIO'),
  bar.music.create('Fado de Lisboa', 'DISSE-TE ADEUS E MORRI'),
  bar.music.create('Fado de Lisboa', 'A TENDINHA'),
  bar.music.create('Fado de Lisboa', 'CAVALO BAIO'),
  bar.music.create('Fado de Lisboa', 'QUINTA FEIRA DA ASCENÇÃO'),
  bar.music.create('Fado de Lisboa', 'REVIVER O PASSADO'),
  bar.music.create('Fado de Lisboa', 'FADO DA MADRAGOA'),
  bar.music.create('Fado de Lisboa', 'BOÉMIO'),
  bar.music.create('Fado de Lisboa', 'FADO TÚLIO'),
  bar.music.create('Fado de Lisboa', 'TEUS OLHOS SÃO DOIS PECADOS'),
  bar.music.create('Fado de Lisboa', 'DESENGANO'),
  bar.music.create('Fado de Lisboa', 'FOI NA TRAVESSA DA PALHA'),
  bar.music.create('Fado de Lisboa', 'GOSTAR DE TI'),
  bar.music.create('Fado de Lisboa', 'SAUDADE VAI-TE EMBORA'),
  bar.music.create('Fado de Lisboa', 'MEU NOME SABE-ME A AREIA'),
  bar.music.create('Fado de Lisboa', 'O FADO MORA EM LISBOA'),
  bar.music.create('Fado de Lisboa', 'O SOL CHAMA POR MIM'),
  bar.music.create('Fado de Lisboa', 'FADO É CONDÃO'),
  bar.music.create('Fado de Lisboa', 'SONHO IMPERFEITO'),
  bar.music.create('Fado de Lisboa', 'O QUE É QUE EU DIGO À SAUDADE'),
  bar.music.create('Fado de Lisboa', 'ZE'),
  bar.music.create('ì CACILHEIRO', 'Fado de Lisboa'),
  bar.music.create('CABELO BRANCO Eì SAUDADE', 'Fado de Lisboa'),
  bar.music.create('CANC', '̧AÞO DA ROSA BRANCA'),
  bar.music.create('Fado de Lisboa', 'O RAPAZ DA CAMISOLA VERDE'),
  bar.music.create('Fado de Lisboa', 'RUGAS DA MINHA CARA'),
  bar.music.create('Fado de Lisboa', 'AI SE OS MEUS OLHOS FALASSEM'),
  bar.music.create('Fado de Lisboa', 'FICA COMIGO A SAUDADE'),
  bar.music.create('Fado de Lisboa', 'PORTO SANTO'),
  bar.music.create('Fado de Lisboa', 'UìLTIMA TOURADA REAL'),
  bar.music.create('Fado de Lisboa', 'CHICO SAPATEIRO'),
  bar.music.create('Fado de Lisboa', 'FADO PUXAVANTE'),
  bar.music.create('Fado de Lisboa', 'SOMBRAS DA MADRUGADA'),
  bar.music.create('Fado de Lisboa', 'DAì TEMPO AO TEMPO'),
  bar.music.create('Fado de Lisboa', 'FRAGATA'),
  bar.music.create('Fado de Lisboa', 'JAì ESTAìS C’OS COPOS'),
  bar.music.create('Fado de Lisboa', 'TUìNICA NEGRA'),
  bar.music.create('Fado de Lisboa', 'FADO LOUCURA(SOU DO FADO)'),
  bar.music.create('Fado de Lisboa', 'Oì PINHEIRO MEU IRMAÞO')
]);
bar.art.create('G', [
  bar.music.create('Gal Costa', 'Um dia de Domingo'),
  bar.music.create('Gemini', 'Dai li dou'),
  bar.music.create('Gentes', 'Marcha do Sporting'),
  bar.music.create('Gestesom', 'Ser benfiquista'),
  bar.music.create('Gestesom', 'Hino oficial f.c.porto'),
  bar.music.create('Gil', 'Nha namorada'),
  bar.music.create('Gilberto Gil', 'Esperando na janela'),
  bar.music.create('Gilberto Gil', 'aquele abraço'),
  bar.music.create('Gilberto Gil', 'Vamos fugir(Gimme your love)'),
  bar.music.create('GNR', 'Sexta-feira'),
  bar.music.create('GNR', 'Asas eléctricas'),
  bar.music.create('GNR', 'ASAS'),
  bar.music.create('GNR', 'TIRANA'),
  bar.music.create('GNR', '+ VALE NUNCA'),
  bar.music.create('GNR', 'Sangue oculto'),
  bar.music.create('GNR', 'Pronúncia do Norte'),
  bar.music.create('GNR', 'Efectivamente'),
  bar.music.create('GNR', 'Quero que tudo vá pr\'o inferno'),
  bar.music.create('GNR', 'Ana Lee'),
  bar.music.create('GNR', 'Dunas'),
  bar.music.create('GNR', 'Tirana'),
  bar.music.create('GNR', 'Sexta-feira (um seu criado)'),
  bar.music.create('GNR', 'Vídeo Maria'),
  bar.music.create('GNR', 'Sub 16'),
  bar.music.create('Gomo', 'Feeling alive'),
  bar.music.create('Gonzaguinha', 'Não Dá Mais Para Segurar (Explode Coração)'),
  bar.music.create('Gonzaguinha', 'Grito de Alerta'),
  bar.music.create('Gonzo', 'Tiras-me do serio'),
  bar.music.create('Grupo de Baile', 'Patchouly'),
  bar.music.create('Guilherme Arantes', 'Nada por mi'),
  bar.music.create('Guilherme Arantes', 'Planeta Água'),
  bar.music.create('Guilherme e santiago', 'a minha saudade'),
  bar.music.create('Gutto', 'Quem seria eu')
]);
bar.art.create('H', [
  // bar.music.create('Hand on Approach', 'IF YOU GIVE UP', 'hands-on-approach-if-you-give-up.mp4'),
  bar.music.create('Hand on Approach', 'IF YOU GIVE UP'),
  bar.music.create('Hands on Approach', 'TÃO PERTO E TÃO LONGE'),
  bar.music.create('Hands on Approach', 'My wonder moon'),
  bar.music.create('Hands on Approach', 'If you give up'),
  bar.music.create('Herman José', 'Saca o saca-rolhas'),
  bar.music.create('Herman José', 'Canção do beijinho'),
  bar.music.create('Herman José', 'Bamos lá cambada'),
  bar.music.create('Herman José', 'ÉS TÃO BOA'),
  bar.music.create('Herman José', 'SERAFIM SAUDADE'),
  bar.music.create('Hermes de Aquino', 'Nuvem Passageira'),
  bar.music.create('Hernany & Gabriel', 'Forte ilusão'),
  bar.music.create('Hernany & Gabriel', 'AMANTE ERRANTE'),
  bar.music.create('Hernany & Gabriel', 'Todo o meu crer'),
  bar.music.create('Heróis do Mar', 'Paixão'),
  bar.music.create('Heróis do Mar', 'Amor'),
  bar.music.create('Heróis do Mar', 'FADO'),
  bar.music.create('Heróis do Mar', 'Só gosto de ti'),
  bar.music.create('Hino GALP Euro2004', 'Será demais pedir a taça'),
  bar.music.create('Hino nacional', 'A Portuguesa'),
  bar.music.create('Humanos', 'MARIA ALBERTINA'),
  bar.music.create('Humanos', 'RUGAS'),
  bar.music.create('Humanos', 'Muda de vida'),
  bar.music.create('Humanos', 'Quero é viver')
]);
bar.art.create('I', [
  bar.music.create('Império dos Sentados', 'Longe de ti'),
  bar.music.create('Império dos Sentados', 'Só por ti'),
  bar.music.create('Império dos Sentados', 'Sempre para te amar'),
  bar.music.create('iran costa', 'balanço do trem'),
  bar.music.create('Iran Costa', 'O BICHO'),
  bar.music.create('Iran Costa', 'O BICHO VAI PEGAR'),
  bar.music.create('Íris', 'Estou alem'),
  bar.music.create('Íris', 'Mal por ti'),
  bar.music.create('Íris', 'Sou metade de ti'),
  bar.music.create('Íris', 'Atira-te ao Mar'),
  bar.music.create('Íris', 'Oh, mãe'),
  bar.music.create('Isabel Campelo', 'Nunca digas adeus'),
  bar.music.create('Ivan Lins', 'Madalena'),
  bar.music.create('Ivan Lins', 'Dinorah, Dinorah'),
  bar.music.create('Ivan Lins', 'Lembra de mim'),
  bar.music.create('Ivan Lins', 'Bilhete'),
  bar.music.create('Ivan Lins', 'Começar de novo'),
  bar.music.create('Ivan Lins', 'Vitoriosa'),
  bar.music.create('Ivan Lins', 'Iluminados'),
  bar.music.create('Ivan Lins', 'Somos todos iguais nesta noite'),
  bar.music.create('Ivan Lins', 'Novo tempo'),
  bar.music.create('Ivan Lins', 'Depende de nós'),
  bar.music.create('Ivan Lins', 'Doce presença'),
  bar.music.create('Ivete Sangalo', 'POEIRA')
]);
bar.art.create('J', [
  bar.music.create('Jáfumega', 'Latina América'),
  bar.music.create('Jáfumega', 'RIBEIRA'),
  bar.music.create('Janita Salomé', 'Senhora do Alcorão'),
  bar.music.create('Joana', 'FUI À TROPA'),
  bar.music.create('joao paulo e daniel', 'estou apaixonado'),
  bar.music.create('João Pedro Pais', 'Não há'),
  bar.music.create('João Pedro Pais', 'Um resto de tudo'),
  bar.music.create('João Pedro Pais', 'Espera por mim'),
  bar.music.create('João Pedro Pais', 'Nada de nada'),
  bar.music.create('João Pedro Pais', 'Mais uma vez'),
  bar.music.create('João Pedro Pais', 'mentira'),
  bar.music.create('João Pedro Pais', 'Ninguém é de ninguém'),
  bar.music.create('João Pedro Pais', 'Um resto de tudo'),
  bar.music.create('João Pedro Pais', 'Nada (de nada)'),
  bar.music.create('João Pedro Pais', 'lembra-te de mim'),
  bar.music.create('João Pedro Pais', 'Um resto de tudo'),
  bar.music.create('João Pedro Pais', 'NÃO HÁ'),
  bar.music.create('João Pedro Pais', 'MENTIRA'),
  bar.music.create('João Pedro Pais', 'MAIS QUE UMA VEZ'),
  bar.music.create('João Pedro Pais', 'LEMBRA-TE DE MIM'),
  bar.music.create('João Pedro Pais', 'NADA DE NADA'),
  bar.music.create('João Pedro Pais', 'LEMBRA-TE DE MIM'),
  bar.music.create('João Pedro Pais', 'TUDO BEM'),
  bar.music.create('João Pedro Pais', 'Mentira'),
  bar.music.create('João Pedro Pais', 'Louco por ti'),
  bar.music.create('João Pedro Pais', 'Lembra-te de mim'),
  bar.music.create('João Portugal', 'Quero-te abraçar'),
  bar.music.create('João Portugal', 'Tudo pode acontecer'),
  bar.music.create('João Portugal', 'Quero-te abraçar'),
  bar.music.create('Jorge Ben', 'Fio maravilha'),
  bar.music.create('Jorge Fernando', 'LUA FEITICEIRA NUA'),
  bar.music.create('Jorge Ferreira', 'ERA POUCO E ACABOU-SE'),
  bar.music.create('Jorge Ferreira', 'A CHUPETA'),
  bar.music.create('Jorge Ferreira', 'MARCHA DO MANDRIÃO'),
  bar.music.create('Jorge Palma', 'Bairro do amor'),
  bar.music.create('Jorge Palma', 'NORTE (o meu)'),
  bar.music.create('Jorge Palma', 'Os demitidos'),
  bar.music.create('Jorge Palma', 'Dá-me lume'),
  bar.music.create('Jorge Palma', 'deixa-me rir'),
  bar.music.create('Jorge Palma', 'DEIXA-ME RIR'),
  bar.music.create('Jorge Palma', 'ESCURIDÃO (VAI POR MIM))'),
  bar.music.create('Jorge Palma', 'ENCOSTA-TE A MIM'),
  bar.music.create('Jorge Palma', 'Deixa-me rir'),
  bar.music.create('Jorge Palma', 'Estrela do mar'),
  bar.music.create('Jorge Palma', 'FRÁGIL'),
  bar.music.create('Jorge Palma', 'Jeremias, o fora da lei'),
  bar.music.create('Jorge Palma', 'Escuridão (vai por mim)'),
  bar.music.create('jose augusto', 'aguenta coraçao'),
  bar.music.create('José Afonso', 'Canção de embalar'),
  bar.music.create('José Cid', '20 Anos'),
  bar.music.create('José Cid', 'Minha música'),
  bar.music.create('José Cid', 'Rosa que te dei'),
  bar.music.create('José Cid', 'Na cabana junto à praia'),
  bar.music.create('José Cid', 'Portugal, Portugal, Portugal'),
  bar.music.create('José Cid', 'vinte anos'),
  bar.music.create('José Cid', 'Na cabana'),
  bar.music.create('José Cid', 'Portuguesa bonita'),
  bar.music.create('José Cid', 'Amar como Jesus amou'),
  bar.music.create('José Cid', 'NA CABANA JUNTO À PRAIA'),
  bar.music.create('José Cid', 'PORTUGAL PORTUGAL'),
  bar.music.create('José Cid', 'ONTEM HOJE E AMANHÃ'),
  bar.music.create('José Cid', 'A MINHA MÚSICA'),
  bar.music.create('José Cid', 'Junto à lareira'),
  bar.music.create('José Cid', 'UM GRANDE, GRANDE AMOR'),
  bar.music.create('José Cid', 'Ontem, hoje e amanhã'),
  bar.music.create('José figueira', 'A cantar o tirolês'),
  bar.music.create('José Figueiras', 'A CANTAR O TIROLÊS'),
  bar.music.create('José Malhoa', '24 Rosas'),
  bar.music.create('José Malhoa', 'BAILE DE VERÃO'),
  bar.music.create('José Malhoa', 'DUAS ROSAS'),
  bar.music.create('José Malhoa', 'SOLTEIRÃO'),
  bar.music.create('José Malhoa', 'NO FUNDO DO SALÃO'),
  bar.music.create('José Malhoa', 'Tudo o que peço a Deus'),
  bar.music.create('José Malhoa', 'Eu vou a todas'),
  bar.music.create('José Malhoa', 'Baile de Verão'),
  bar.music.create('José Malhoa', 'Vai ter que rezar'),
  bar.music.create('José Malhoa', 'Toca a todos'),
  bar.music.create('jotinha/gino liver', 'me usa'),
  bar.music.create('Juanes', 'La Camisa Negra'),
  bar.music.create('Juka', 'Allo cherry'),
  bar.music.create('jurandir dias', 'apaixonada'),
  bar.music.create('Juve leo', 'Só eu sei')
]);
bar.art.create('K', [
  bar.music.create('Karametade', 'Morango do nordeste'),
  // bar.music.create('Keane', 'Somewhere', 'keane-somewhere.mp4'),
  bar.music.create('Keane', 'Somewhere'),
  bar.music.create('Kelly key', 'Baba'),
  bar.music.create('kely key', 'anjo'),
  bar.music.create('Kid Abelha', 'La Bella Luna'),
  bar.music.create('King Africa', 'LA BOMBA'),
  bar.music.create('King Caribe', 'TESOURO DO PIRATA'),
  bar.music.create('KIZOMBA Araketu', 'MAL ACOSTUMADO (V. KIZ.)'),
  bar.music.create('KIZOMBA Calu', 'dois (kizomba)'),
  bar.music.create('KIZOMBA Calú', 'DOIS (VERSÃO KIZOMBA)'),
  bar.music.create('KIZOMBA Don Kikas', 'ESPERANÇA MORIBUNDA'),
  bar.music.create('KIZOMBA Eduardo Paim', 'A MINHA VIZINHA'),
  bar.music.create('KIZOMBA Euclides da Lomba', 'CASO DE AMOR ( KIZOMBA )'),
  bar.music.create('KIZOMBA Euclides da Lomba', 'DESEJO MALANDRO'),
  bar.music.create('KIZOMBA Gil', 'NOS LÍDER'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'AMAR-TE ASSIM (KIZOMBA)'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'YOLANDA'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'ISABELLA'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'OH YARA ( KIZOMBA )'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'TÃO SOZINHO'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'TÃO APAIXONADO ( KIZOMBA )'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'EU QUERO-TE ASSIM TANTO'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'SAUDADES DE LUANDA'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'SONHO LINDO'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'O TEMPO PASSA'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'DESEJO MEU'),
  bar.music.create('KIZOMBA Irmãos Verdade', 'Yolanda'),
  bar.music.create('KIZOMBA J. C.', 'VOCÊ ROUBOU A MINHA VIDA'),
  bar.music.create('KIZOMBA Juka', 'ALLÔ CHERRY'),
  bar.music.create('KIZOMBA Lura', 'NA RI NA ( KIZOMBA )'),
  bar.music.create('KIZOMBA Pato', 'AMOR INESQUECÍVEL'),
  bar.music.create('KIZOMBA Paulo Flores', 'CHERRY'),
  bar.music.create('KIZOMBA Walter', 'MORANGO DO NORDESTE (Kizomba)')
]);
bar.art.create('L', [
  bar.music.create('l.s. jack', 'Carla'),
  bar.music.create('Lara fabian', 'Meu grande amor'),
  bar.music.create('Lara li', 'Telepatia'),
  bar.music.create('Las Ketchup', 'ASEREJE'),
  bar.music.create('Leandro & Leonardo', 'PAZ NA CAMA'),
  bar.music.create('Leandro & Leonardo', 'Temporal de Amor'),
  bar.music.create('Leandro & Leonardo', 'eu juro'),
  bar.music.create('Lena d’Água', 'Sempre que o amor me quiser'),
  bar.music.create('Lenine', 'Paciência'),
  bar.music.create('Levity', 'Rosinha'),
  bar.music.create('Los centelhas', 'Ei toro y la luna'),
  bar.music.create('Los hermanos', 'Anna Júlia'),
  bar.music.create('Los Lobos', 'LA BAMBA'),
  bar.music.create('Los Locos', 'TUM TUM'),
  bar.music.create('Los morenos', 'Levantando lás manos'),
  bar.music.create('Los Morenos', 'LEVANTANDO MANOS'),
  bar.music.create('Los Morenos', 'QUE LA DETENGAN'),
  bar.music.create('Los Vísperas de Car.', 'PARA NO VER-TE MAS'),
  bar.music.create('lucas e mateus', 'preciso do teu prazer'),
  bar.music.create('lucas e mateus', 'dormi na praça'),
  bar.music.create('Lúcia Moniz', 'Dizer que não'),
  bar.music.create('Lúcia Moniz', 'Try again'),
  bar.music.create('Luis Filipe Reis', 'O que é meu é meu'),
  bar.music.create('Luis Filipe Reis', 'NÃO TE OUVI DIZER ADEUS-VOU GUARDAR RECORDAÇÕES'),
  bar.music.create('Luís Filipe Reis', 'PEDE MAIS'),
  bar.music.create('Luís Filipe Reis', 'O QUE É MEU É MEU'),
  bar.music.create('Luis Filipe Reis', 'Não te ouvi dizer adeus'),
  bar.music.create('Luís Portela', 'Anda, anda no ar'),
  bar.music.create('Luís Represas', 'Neva sobre a marginal'),
  bar.music.create('Luís Represas', 'Da próxima vez'),
  bar.music.create('Luís Represas', 'Acontece (às vezes)'),
  bar.music.create('Luís Represas', 'No escuro'),
  bar.music.create('Luís Represas', 'Feiticeira pt.es'),
  bar.music.create('Luís Represas', 'Perdidamente'),
  bar.music.create('Luís Represas', 'Ao canto da noite'),
  bar.music.create('Luís Represas', 'Ando em busca de palavras'),
  bar.music.create('Luís Represas', 'Feiticeira'),
  bar.music.create('Luís Represas', 'Foi como foi'),
  bar.music.create('luiz gonzaga/humberto teixeira', 'asa branca'),
  bar.music.create('luiz gonzaga/jose marcolino', 'numa sala de reboco'),
  bar.music.create('luka', 'to nem ai'),
  bar.music.create('Lunáticos', 'Estou na lua')
]);
bar.art.create('M', [
  bar.music.create('Madalena iglesias', 'Ele e ela'),
  bar.music.create('Madredeus', 'Haja o que houver'),
  bar.music.create('Madredeus', 'A vaca de fogo'),
  bar.music.create('Madredeus', 'Ó LUZ DA ALEGRIA'),
  bar.music.create('Madredeus', 'O TEJO'),
  bar.music.create('Madredeus', 'Vem'),
  bar.music.create('Madredeus', 'O pastor'),
  bar.music.create('Madredeus', 'Moro em Lisboa'),
  bar.music.create('Mafalda veiga', 'Pedra filosofal'),
  bar.music.create('Mafalda veiga', 'Em cada lugar'),
  bar.music.create('Mafalda Veiga', 'Uma gota'),
  bar.music.create('Mafalda Veiga', 'O lume'),
  bar.music.create('Mafalda Veiga & Jorge Palma', 'Tatuagens'),
  bar.music.create('Mafalda Veiga', 'Restolho'),
  bar.music.create('Mafalda Veiga', 'Planície'),
  bar.music.create('Mafalda Veiga', 'ILHA'),
  bar.music.create('Mafalda Veiga', 'Cada Lugar teu'),
  bar.music.create('Mafalda Veiga', 'A ilha'),
  bar.music.create('Malhão', 'Tradicional'),
  bar.music.create('Mamonas Assassinas', 'Vira Vira'),
  bar.music.create('Manuel Freire', 'Pedra Filosofal'),
  bar.music.create('Manuela Bravo', 'Sobe balão sobe'),
  bar.music.create('Mão Morta', 'Budapeste'),
  bar.music.create('Marante', 'CANELA E MEL'),
  bar.music.create('Marco Horácio', 'Fado das Barracas'),
  bar.music.create('Marco Horácio', 'Mulher maluca'),
  bar.music.create('Marco Paulo', 'Taras e manias'),
  bar.music.create('Marco Paulo', 'TARAS E MANIAS'),
  bar.music.create('Marco Paulo', 'NOSSA SENHORA'),
  bar.music.create('Marco Paulo', 'MORENA, OH MORENITA'),
  bar.music.create('Marco Paulo', 'MARAVILHOSO CORAÇÃO'),
  bar.music.create('Marco Paulo', 'NINGUÉM NINGUÉM'),
  bar.music.create('Marco Paulo', 'Eu tenho dois amores'),
  bar.music.create('Marco Paulo', 'Vendaval'),
  bar.music.create('Marco Paulo', 'O amor é louco'),
  bar.music.create('Marco Paulo', 'Eu tenho dois amores'),
  bar.music.create('Marco Paulo', 'Maravilhoso coração'),
  bar.music.create('Marco Paulo', 'Taras e manias'),
  bar.music.create('Marco Paulo', 'Só nós dois'),
  bar.music.create('Marco Paulo', 'MORENA MORENITA'),
  bar.music.create('Marco Paulo', 'Ninguém, ninguém'),
  bar.music.create('Maria Armanda', 'Eu vi um sapo'),
  bar.music.create('Maria Bethânia', 'Ronda'),
  bar.music.create('Maria Bethânia', 'Coração ateu'),
  bar.music.create('Maria José Valério', 'Marcha do Sporting'),
  bar.music.create('Maria León & Rui Veloso', 'Caminhando até ti'),
  bar.music.create('maria lisboa', 'tira a maozinha'),
  bar.music.create('Maria Lisboa', 'TIRA A MÃOZINHA DAÍ'),
  bar.music.create('Marina', 'Homem de Nazaré'),
  bar.music.create('Mário Gil', 'PELOS CAMINHOS DE PORTUGAL'),
  bar.music.create('Marisa Monte', 'Andanças'),
  bar.music.create('Mariza', 'Desejo'),
  bar.music.create('Mariza', 'Fado curvo'),
  bar.music.create('Mariza', 'FADO TORDO'),
  bar.music.create('Mariza', 'Oiça lá Sr. Vinho'),
  bar.music.create('Mariza', 'MEU FADO MEU'),
  bar.music.create('Mariza', 'Ó gente da minha terra'),
  bar.music.create('Mariza', 'Cavaleiro monge'),
  bar.music.create('Marta plantier', 'Remédio santo'),
  bar.music.create('Martinho da Vila', 'Mulheres'),
  bar.music.create('Maskavo', 'Um anjo do céu'),
  bar.music.create('Mau Maria', 'Vai-te lixar'),
  bar.music.create('Max', 'Pomba branca'),
  bar.music.create('Max', 'A mula da cooperativa'),
  bar.music.create('Maxi', 'Anjo selvagem'),
  bar.music.create('MDA', 'Por quem não esqueci (versão dance)'),
  bar.music.create('Meninas xi bom', 'Xi bom bom'),
  bar.music.create('Menito Ramos', 'O mundo não acaba aqui'),
  bar.music.create('Ménito Ramos', 'A noite grita por mim'),
  bar.music.create('Mercado Negro', 'LEOA TIGRESA'),
  bar.music.create('Mercado Negro', 'Oh, lua (encontro)'),
  bar.music.create('Mercúrio cromos', 'Indecências (luzia)'),
  bar.music.create('Metamorfose ambulante - Raul Seixas', 'Brasil Pandeiro'),
  bar.music.create('Micaela', 'Gugu dada'),
  bar.music.create('Micaela', 'ASTRAL'),
  bar.music.create('Micaela', 'Chupa no Dedo'),
  bar.music.create('Micaela', 'Desliga a Televisão'),
  bar.music.create('Mickael Carreira', 'DEPOIS DESSA NOITE'),
  bar.music.create('Mickael Carreira', 'BAILA P’RA MIM'),
  bar.music.create('Mickael Carreira', 'NÃO ME ESQUEÇO DE TI'),
  bar.music.create('Mickael Carreira', 'O AMOR PODE ESPERAR'),
  bar.music.create('Mickael Carreira', 'MEXE BEM DEMAIS'),
  bar.music.create('Mickael Carreira', 'POR AMOR VOU ATÉ AO FIM'),
  bar.music.create('Mickael e Tony Carreira', 'FILHO E PAI'),
  bar.music.create('miguel & andre', 'falar de amor'),
  bar.music.create('Miguel & André', 'EU SEMPRE TE AMEI'),
  bar.music.create('Miguel & André', 'A ÚLTIMA DANÇA'),
  bar.music.create('Miguel & André', 'FALAR DE AMOR'),
  bar.music.create('Miguel & André', 'Toda a razão do meu viver'),
  bar.music.create('Miguel e André', 'Não da pra ser feliz'),
  bar.music.create('Miguel & André', 'Mar Deserto'),
  bar.music.create('Milénio', 'Meu universo é tu'),
  bar.music.create('Milénio', 'ESTÁS ONDE NÃO ESTÁS'),
  bar.music.create('Milton César', 'A namorada que sonhei'),
  bar.music.create('Milton Nascimento', 'nos bailes da vida'),
  bar.music.create('Milton Nascimento', 'Travessia'),
  bar.music.create('Mónica Sintra', 'Condenada a sofrer por ti'),
  bar.music.create('Mónica Sintra', 'EU JÁ SOFRI DEMAIS'),
  bar.music.create('Mónica Sintra', 'anjo da guarda'),
  bar.music.create('Mónica Sintra', 'Há quanto tempo'),
  bar.music.create('Mónica Sintra', 'HÁ QUANTO TEMPO'),
  bar.music.create('Mónica Sintra', 'SALSA'),
  bar.music.create('Mónica Sintra', 'EU ESQUECI DE LEMBRAR DE MIM'),
  bar.music.create('Mónica Sintra', 'P\'RA SEMPRE TUA'),
  bar.music.create('Mónica Sintra', 'Dava-te tudo'),
  bar.music.create('Mónica Sintra', 'Na minha cama com ela'),
  bar.music.create('Mónica Sintra', 'Afinal havia outra'),
  bar.music.create('Mónica Sintra', 'Vem dançar esta salsa'),
  bar.music.create('Moraes Moreira', 'Pombo Correio'),
  bar.music.create('Mosca', 'Para no verte mas')
]);
bar.art.create('N', [
  bar.music.create('nando cordel', 'jogo de cintura'),
  bar.music.create('Natércia Barreto', 'Óculos de sol'),
  bar.music.create('Né Ladeiras', 'Sonho azul'),
  bar.music.create('Nel Monteiro', 'Azar na praia'),
  bar.music.create('Nelly Furtado', 'I\'M LIKE A BIRD'),
  bar.music.create('Nelly Furtado', 'FORÇA'),
  bar.music.create('Nelson Cavaquinho', 'Folhas secas'),
  bar.music.create('Nelson Ned', 'domingo a tarde'),
  bar.music.create('Nelson Ned', 'Tudo passará'),
  bar.music.create('Némanus', 'DANÇANDO KIZOMBA'),
  bar.music.create('Némanus', 'Sonho de aventura'),
  bar.music.create('Némanus', 'Não quero ninguém'),
  bar.music.create('Netinho', 'Musica baiana'),
  bar.music.create('Netinho', 'Menina linda'),
  bar.music.create('Netinho', 'Preciso de você'),
  bar.music.create('Netinho', 'Beijo na boca'),
  bar.music.create('Netinho', 'Milla'),
  bar.music.create('Ney Matogrosso', 'Bandoleiro'),
  bar.music.create('Ney Matogrosso', 'Homem com H'),
  bar.music.create('Ney Matogrosso', 'Balada do Louco'),
  bar.music.create('Nikita', 'Só Deus'),
  bar.music.create('Nilton César', 'ADEUS SOLIDÃO'),
  bar.music.create('Nilton César', 'A NAMORADA QUE SONHEI'),
  bar.music.create('Nilton César', 'ESPERA UM POUCO'),
  bar.music.create('Non stop', 'ao limite eu vou'),
  bar.music.create('Non stop', 'Basta um sorriso'),
  bar.music.create('Non Stop', 'AO LIMITE EU VOU'),
  bar.music.create('Non Stop', 'BASTA UM SORRISO'),
  bar.music.create('Non Stop', 'OLHAR P\'RA TI'),
  bar.music.create('Novos Baianos', 'A sua'),
  bar.music.create('Nucha', 'Anda (vou ficar a janela)')
]);
bar.art.create('O-P', [
  bar.music.create('Ornatos Violeta', 'COISAS'),
  bar.music.create('Oswaldo Montenegro', 'Lua e Flor'),
  bar.music.create('Paco Bandeira', 'A minha cidade'),
  bar.music.create('Paco Bandeira', 'Ternura dos 40'),
  bar.music.create('Paco Bandeira', 'Chula da livração'),
  bar.music.create('Paco Bandeira', 'É POR ISSO QUE EU VIVO'),
  bar.music.create('Paco Bandeira', 'JOÃO SARAMAGO'),
  bar.music.create('Paco Bandeira', 'Minha 5ª sinfonia'),
  bar.music.create('Papas da Língua', 'EU SEI'),
  bar.music.create('Paralamas do Sucesso', 'Outra Vez'),
  bar.music.create('Patrícia Candoso', 'Ainda acredito'),
  bar.music.create('Paula Teixeira', 'SONHA COMIGO'),
  bar.music.create('Paula Teixeira', 'Acreditar em mim'),
  bar.music.create('Paulo Alexandre', 'VINHO VERDE'),
  bar.music.create('Paulo de Carvalho', 'Meninos de Huambo'),
  bar.music.create('Paulo de Carvalho', 'E depois do Adeus'),
  bar.music.create('Paulo de Carvalho', 'Maria vida fria'),
  bar.music.create('Paulo de Carvalho', 'Flôr sem tempo'),
  bar.music.create('Paulo de Carvalho', 'QUANDO UM HOMEM QUISER'),
  bar.music.create('Paulo de Carvalho', 'Nini dos meus quinze anos'),
  bar.music.create('Paulo de Carvalho', 'Gostava de vos ver aqui'),
  bar.music.create('Paulo Gonzo', 'Acordar'),
  bar.music.create('Paulo Gonzo', 'SEM PRESSA (este lugar)'),
  bar.music.create('Paulo Gonzo', 'FAZ-ME BEM'),
  bar.music.create('Paulo Gonzo', 'So do I'),
  bar.music.create('Paulo Gonzo', 'Jardins proibidos'),
  bar.music.create('Paulo Gonzo', 'Leve beijo triste'),
  bar.music.create('Paulo Gonzo', 'SOMOS BENFICA'),
  bar.music.create('Paulo Gonzo', 'PAGAVA PRA VER'),
  bar.music.create('Paulo Gonzo', 'Jardins proibidos'),
  bar.music.create('Paulo Gonzo', 'Sei-te de cor'),
  bar.music.create('Paulo Gonzo', 'Dei-te quase tudo'),
  bar.music.create('Paulo Gonzo', 'Pagava para ver'),
  bar.music.create('Paulo Gonzo', 'Falamos depois'),
  bar.music.create('Paulo Ricardo', 'Dois'),
  bar.music.create('Pedro Abrunhosa', 'Eu não sei quem te perdeu'),
  bar.music.create('Pedro Abrunhosa', 'Se eu fosse um dia o teu olhar'),
  bar.music.create('Pedro Abrunhosa', 'EU ESTOU AQUI'),
  bar.music.create('Pedro Abrunhosa', 'Lua'),
  bar.music.create('Pedro Abrunhosa', 'Momento'),
  bar.music.create('Pedro Abrunhosa', 'Tudo o que eu te dou'),
  bar.music.create('Pedro Abrunhosa', 'Socorro'),
  bar.music.create('Pedro Abrunhosa', 'Momento (uma espécie de céu)'),
  bar.music.create('Pedro Abrunhosa', 'Tudo o que eu te dou'),
  bar.music.create('Pedro Abrunhosa', 'Se eu fosse um dia o teu olhar'),
  bar.music.create('Pedro Abrunhosa', 'Não posso mais'),
  bar.music.create('Pedro Abrunhosa', 'Eu estou aqui'),
  bar.music.create('Pedro Barroso', 'MENINA DOS OLHOS DE ÁGUA'),
  bar.music.create('Pedro e os Apóstolos', 'No meu céu'),
  bar.music.create('Pedro e os Apóstolos', 'FAZ FIGAS'),
  bar.music.create('Pedro Khima', 'ESFERA (POR SINAL)'),
  bar.music.create('Pedro Miguéis', 'Coisas que não esqueço'),
  bar.music.create('Pedro Miguéis', 'Será sempre um olhar'),
  bar.music.create('peninha', 'sozinho'),
  bar.music.create('Peste e sida', 'Bué da baldas'),
  bar.music.create('Peste e sida', 'Sol da Caparica'),
  bar.music.create('Pixinguinha', 'Carinhoso'),
  bar.music.create('Pólo norte', 'Se eu voltasse atrás'),
  bar.music.create('Pólo Norte', 'PURA INOCÊNCIA'),
  bar.music.create('Pólo Norte', 'UMA QUESTÃO DE PALAVRAS'),
  bar.music.create('Pólo Norte', 'Aprender a ser feliz'),
  bar.music.create('Pólo Norte', 'Lisboa'),
  bar.music.create('Pólo Norte', 'Grito'),
  bar.music.create('Pólo Norte', 'Um dia'),
  bar.music.create('Pólo Norte', 'Pura inocência'),
  bar.music.create('Pólo Norte', 'Deixa o mundo girar'),
  bar.music.create('Popular', 'PARABÉNS A VOCÊ'),
  bar.music.create('Popular', 'É NATAL, É NATAL'),
  bar.music.create('Popular', 'Lisboa não sejas francesa'),
  bar.music.create('Popular', 'Cheira a Lisboa'),
  bar.music.create('Popular', 'Mulher gorda'),
  bar.music.create('Popular', 'Bailinho da Madeira'),
  bar.music.create('Popular', 'Ao passar a ribeirinha'),
  bar.music.create('Popular', 'CABECINHA NO OMBRO'),
  bar.music.create('Popular', 'UMA CASA PORTUGUESA (FADO CANÇÃO)'),
  bar.music.create('Popular', 'Ó MALHÃO MALHÃO'),
  bar.music.create('Popular', 'Cantiga da rua'),
  bar.music.create('Popular', 'Ó rama ó que linda rama'),
  bar.music.create('Popular', 'Mãe querida'),
  bar.music.create('Popular', 'Apita o combóio'),
  bar.music.create('Popular', 'Ó Zé aperta o laço'),
  bar.music.create('Popular', 'Pezinho da Vila'),
  bar.music.create('Popular', 'Laurindinha'),
  bar.music.create('Popular', 'Oliveira da Serra'),
  bar.music.create('Popular', 'Baile dos passarinhos'),
  bar.music.create('Popular', 'Ouvi o Passarinho'),
  bar.music.create('Popular', 'O cochicho'),
  bar.music.create('Popular', 'CHIBINHA'),
  bar.music.create('Popular', 'TREM DAS ONZE'),
  bar.music.create('Porquinhos da Ilda', 'Canguru'),
  bar.music.create('Porto/Benfica/spc', 'Rapsódia dos clubes')
]);
bar.art.create('Q', [
  bar.music.create('Qreen Windows', 'Os 20 anos'),
  bar.music.create('Quim Barreiros', 'Eu tou maluco'),
  bar.music.create('Quim Barreiros', 'Tira a roupa'),
  bar.music.create('Quim Barreiros', 'Mestre de culinária'),
  bar.music.create('Quim Barreiros', 'Agua de coco'),
  bar.music.create('Quim Barreiros', 'Melhor dia \'pra casar'),
  bar.music.create('Quim Barreiros', 'Depois da uma'),
  bar.music.create('Quim Barreiros', 'meias de renda'),
  bar.music.create('quim barreiros', 'comer comer'),
  bar.music.create('Quim Barreiros', 'EU TOU MALUCO'),
  bar.music.create('Quim Barreiros', 'TIRA A ROUPA'),
  bar.music.create('Quim Barreiros', 'ÁGUA DE CÔCO'),
  bar.music.create('Quim Barreiros', 'MELHOR DIA PRA CASAR'),
  bar.music.create('Quim Barreiros', 'DEPOIS DA UMA'),
  bar.music.create('Quim Barreiros', 'MEIAS DE RENDA'),
  bar.music.create('Quim Barreiros', 'AEROPORTO DE MOSQUITO'),
  bar.music.create('Quim Barreiros', 'NA TUA CASA...OUTRO MACHO'),
  bar.music.create('Quim Barreiros', 'MINHA SOGRA'),
  bar.music.create('Quim Barreiros', 'OLHA O CHEIRO QUE A ROSA DÁ'),
  bar.music.create('Quim Barreiros', 'COMER, COMER'),
  bar.music.create('Quim Barreiros', 'A GARAGEM DA VIZINHA'),
  bar.music.create('Quim Barreiros', 'A CABRITINHA'),
  bar.music.create('Quim Barreiros', 'A COISA'),
  bar.music.create('Quim Barreiros', 'Na tua casa tá entrando outro macho'),
  bar.music.create('Quim Barreiros', 'A garagem da vizinha'),
  bar.music.create('Quim Barreiros', 'O ténis'),
  bar.music.create('Quim Barreiros', 'A empregada'),
  bar.music.create('Quim Barreiros', 'Bacalhau à portuguesa'),
  bar.music.create('Quim Barreiros', 'Mestre de Culinária'),
  bar.music.create('Quim Barreiros', 'Casado também namora'),
  bar.music.create('Quim Barreiros', 'A padaria'),
  bar.music.create('Quim Barreiros *', 'A CABRITINHA'),
  bar.music.create('Quim Barreiros', 'Depois da uma'),
  bar.music.create('Quim Barreiros', 'Mestre de culinária'),
  bar.music.create('Quim Barreiros *', 'NUNCA GASTES TUDO'),
  bar.music.create('Quim Gouveia', 'Biagra'),
  bar.music.create('Quinta do bill', 'Filhos da nação'),
  bar.music.create('Quinta do Bill', 'Se te amo')
]);
bar.art.create('R', [
  bar.music.create('Rádio Macau', 'Anzol'),
  bar.music.create('Rádio Macau', 'A vida num só dia'),
  bar.music.create('Rádio Macau', 'Acordar'),
  bar.music.create('Rádio Macau', 'O elevador da gloria'),
  bar.music.create('Reginaldo Rossi', 'Garçon'),
  bar.music.create('Resistência', 'Amanha é sempre longe de mais'),
  bar.music.create('Resistência', 'Nasce selvagem'),
  bar.music.create('Resistência', 'A noite'),
  bar.music.create('Ricardo & Henrique', 'VALE A PENA AMAR DE NOVO'),
  bar.music.create('Ricardo Azevedo', 'PEQUENO T2'),
  bar.music.create('Ricardo&henrique', 'Vale a pena amar'),
  bar.music.create('Rio grande', 'Postal dos correios'),
  bar.music.create('Rio Grande', 'A Fisga'),
  bar.music.create('Rio Negro & Solimões', 'NA SOLA DA BOTA'),
  bar.music.create('rita de cássia', 'meu vaqueiro meu peao'),
  bar.music.create('Rita Guerra & Beto', 'ACREDITAR'),
  bar.music.create('Rita guerra', 'No meio da escuridão'),
  bar.music.create('Rita Guerra', 'SENTIMENTO'),
  bar.music.create('Rita Guerra', 'Deixa-me sonhar'),
  bar.music.create('Rita Guerra', 'Chegar a ti'),
  bar.music.create('Rita Guerra & Beto', 'ACREDITAR'),
  bar.music.create('Rita Guerra & Beto', 'É PORQUE A GENTE SENTE'),
  bar.music.create('Rita guerra e beto', 'Brincando com o fogo'),
  bar.music.create('Rita guerra e beto', 'Desencontros'),
  bar.music.create('Rita Lee', 'flagra'),
  bar.music.create('Rita Lee', 'Mania de você'),
  bar.music.create('Rita Lee', 'Lança Perfume'),
  bar.music.create('Ritchie Valens', 'La Bamba'),
  bar.music.create('Ritual Tejo', 'Foram cardos foram prosas'),
  bar.music.create('Ritual Tejo', 'Nascer outra vez'),
  bar.music.create('rivanil', 'cumade conpade'),
  bar.music.create('rmãos Verdades', 'Isabella'),
  bar.music.create('Roberta Miranda', 'São tantas coisas'),
  bar.music.create('Roberta miranda', 'Champanhe'),
  bar.music.create('Roberta Miranda', 'Vá com Deus'),
  bar.music.create('Roberto Carlos', 'Se o amor se vai'),
  bar.music.create('Roberto Carlos', 'Tudo para'),
  bar.music.create('Roberto Carlos', 'Coisa bonita'),
  bar.music.create('Roberto Carlos', 'A namorada de um amigo meu'),
  bar.music.create('Roberto Carlos', 'Quando'),
  bar.music.create('Roberto Carlos', 'Lady Laura'),
  bar.music.create('Roberto Carlos', 'as baleias'),
  bar.music.create('Roberto Carlos', 'Mulher de 40'),
  bar.music.create('Roberto Carlos', 'Calhambeque'),
  bar.music.create('Roberto Carlos', 'Emoções'),
  bar.music.create('Roberto Carlos', 'As baleias'),
  bar.music.create('Roberto Carlos', 'Outra Vez'),
  bar.music.create('Roberto Carlos', 'TUDO PÁRA'),
  bar.music.create('Roberto Carlos', 'COISA BONITA (GORDINHA)'),
  bar.music.create('Roberto Carlos', 'NAMORADA DE UM AMIGO MEU'),
  bar.music.create('Roberto Carlos', 'QUANDO'),
  bar.music.create('Roberto Carlos', 'LADY LAURA'),
  bar.music.create('Roberto Carlos', 'MEU QUERIDO...VELHO... AMIGO'),
  bar.music.create('Roberto Carlos', 'MULHER PEQUENA'),
  bar.music.create('Roberto Carlos', 'O BAILE DA FAZENDA'),
  bar.music.create('Roberto Carlos', 'CAMINHONEIRO'),
  bar.music.create('Roberto Carlos', 'AMOR SEM LIMITE'),
  bar.music.create('Roberto Carlos', 'QUERO QUE VÁ PRO INFERNO'),
  bar.music.create('Roberto Carlos', 'FERA FERIDA'),
  bar.music.create('Roberto Carlos', 'CAVALGADA'),
  bar.music.create('Roberto Carlos', 'POR ELA'),
  bar.music.create('Roberto Carlos', 'CAMA E MESA'),
  bar.music.create('Roberto Carlos', 'MULHER DE 40'),
  bar.music.create('Roberto Carlos', 'O VELHO CAMINHONEIRO'),
  bar.music.create('Roberto Carlos', 'ARRASTA UMA CADEIRA'),
  bar.music.create('Roberto Carlos', 'TERÇO'),
  bar.music.create('Roberto Carlos', 'TODAS AS MANHÃS'),
  bar.music.create('Roberto Carlos', 'ILEGAL, IMORAL OU ENGORDA'),
  bar.music.create('Roberto Carlos', 'O CADILLAC'),
  bar.music.create('Roberto Carlos', 'Quero que tudo vá para o inferno'),
  bar.music.create('Roberto leal', 'Bate o pé'),
  bar.music.create('Roberto leal', 'Português brasileiro'),
  bar.music.create('Roberto Leal', 'PORTUGUÊS BRASILEIRO'),
  bar.music.create('Roberto Leal', 'Ó COMADRE MARI\'BENTA'),
  bar.music.create('Roberto Leal', 'DE AMADO A PESSOA'),
  bar.music.create('Roberto Leal', 'Dá cá um beijo'),
  bar.music.create('Roberto Leal', 'Que bela vida'),
  bar.music.create('Rodrigo', 'SE TU EXISTES'),
  bar.music.create('Romana', 'Não és homem para mim'),
  bar.music.create('Romana', 'Assim é que tu me levas'),
  bar.music.create('Romana', 'Já não sou bebé'),
  bar.music.create('Romana e ágata', 'De mulher para mulher'),
  bar.music.create('roupa nova', 'linda demais'),
  bar.music.create('roupa nova', 'anjo'),
  bar.music.create('Roupa Nova', 'Dona'),
  bar.music.create('Roupa Nova', 'Linda demais'),
  bar.music.create('Roupa Nova', 'Whisky à Go Go'),
  bar.music.create('Rouxinol Faduncho', 'CÃES DE LOIÇA'),
  bar.music.create('Rouxinol Faduncho', 'FADO BEAT'),
  bar.music.create('Rui Bandeira', 'COMO TUDO COMEÇOU'),
  bar.music.create('Rui Bandeira', 'CORAÇÃO ESQUECIDO'),
  bar.music.create('Rui Bandeira', 'EU QUERO MAIS DE TI'),
  bar.music.create('Rui de Mascarenhas', 'Pauliteiros do Douro'),
  bar.music.create('Rui Veloso', 'Chico fininho'),
  bar.music.create('Rui Veloso', 'Nunca me esqueci de ti'),
  bar.music.create('Rui Veloso', 'Prometido é devido'),
  bar.music.create('Rui Veloso', 'Não há estrelas no céu'),
  bar.music.create('Rui Veloso', 'A paixão'),
  bar.music.create('Rui Veloso', 'Não há estrelas no céu'),
  bar.music.create('Rui Veloso', 'Canção do alarme'),
  bar.music.create('Rui Veloso', 'Porto sentido'),
  bar.music.create('Rui Veloso', 'O prometido e devido'),
  bar.music.create('Rui Veloso', 'não me mintas'),
  bar.music.create('Rui Veloso', 'baile da paroquia'),
  bar.music.create('Rui Veloso', 'NÃO HÁ ESTRELAS NO CÉU'),
  bar.music.create('Rui Veloso', 'O PROMETIDO É DEVIDO'),
  bar.music.create('Rui Veloso', 'PRIMEIRO BEIJO'),
  bar.music.create('Rui Veloso', 'MÁQUINA ZERO'),
  bar.music.create('Rui Veloso', 'PAIXÃO'),
  bar.music.create('Rui Veloso', 'NUNCA ESQUECI DE TI'),
  bar.music.create('Rui Veloso', 'PORTO SENTIDO'),
  bar.music.create('Rui Veloso', 'TODO O TEMPO DO MUNDO'),
  bar.music.create('Rui Veloso', 'BAILE DA PARÓQUIA'),
  bar.music.create('Rui Veloso', 'NÃO ME MINTAS'),
  bar.music.create('Rui Veloso', 'CANÇÃO DE ALTERNE'),
  bar.music.create('Rui Veloso', 'BRILHO DENTAL'),
  bar.music.create('Rui Veloso', 'Todo o tempo do mundo'),
  bar.music.create('Rui Veloso', 'Maquina zero'),
  bar.music.create('Rui Veloso', 'Maquina zero'),
  bar.music.create('Rui Veloso', 'Porto Côvo'),
  bar.music.create('Rui Veloso', 'Lado lunar'),
  bar.music.create('Rui Veloso', 'Chico Fininho'),
  bar.music.create('Rui Veloso', 'Nunca me esqueci de ti'),
  bar.music.create('Rui Veloso', 'Cavaleiro andante'),
  bar.music.create('Rui Veloso', 'Sei de uma camponesa'),
  bar.music.create('Rui Veloso', 'Bairro do Oriente'),
  bar.music.create('Rui Veloso', 'Um café e um bagaço'),
  bar.music.create('Rui Veloso', 'AS REGRAS DA SENSATEZ'),
  bar.music.create('Rui Veloso', 'NÃO INVOQUEM O AMOR EM VÃO'),
  bar.music.create('Rui Veloso', 'Lado lunar'),
  bar.music.create('Rui Veloso', 'A Paixão'),
  bar.music.create('Rui Veloso', 'Porto sentido'),
  bar.music.create('Rui Veloso', 'Já não há canções de amor'),
  bar.music.create('Rui Veloso', 'A ilha'),
  bar.music.create('Rui Veloso', 'porto sentido'),
  bar.music.create('Rui Veloso', 'O prometido é devido'),
  bar.music.create('Rui Veloso', 'BEIRÃ'),
  bar.music.create('Rui Veloso', 'ESTRELA DO ROCK\'N ROLL'),
  bar.music.create('Rui Veloso', 'LIMPA CORAÇÕES'),
  bar.music.create('Rui Veloso', 'CANÇÃO DE ALTERNE'),
  bar.music.create('Rui Veloso', 'Não há estrelas no céu'),
  bar.music.create('Rui Veloso', 'Jura'),
  bar.music.create('Rui Veloso', 'Fado do ladrão enamorado'),
  bar.music.create('Rui Veloso (acústico)', 'OS VELHOS DO JARDIM'),
  bar.music.create('Rui Veloso', 'Beirã'),
  bar.music.create('Rui Veloso', 'Canção de alterne'),
  bar.music.create('Rui Veloso (acústico)', 'DIA DE PASSEIO'),
  bar.music.create('Ruth Marlene', 'Bora bora (bora dai)'),
  bar.music.create('Ruth Marlene', 'Quanto mais melhor'),
  bar.music.create('Ruth Marlene', 'BORA, BORA'),
  bar.music.create('Ruth Marlene', 'QUANTO MAIS MELHOR'),
  bar.music.create('Ruth Marlene', 'QUERES É FESTA'),
  bar.music.create('Ruth Marlene', 'ENCOSTA QUE É BOM'),
  bar.music.create('Ruth Marlene', 'Mexe mexe que eu gosto'),
  bar.music.create('Ruth Marlene', 'A moda do Pisca Pisca'),
  bar.music.create('Ruth Marlene', 'Cola Cola'),
  bar.music.create('Ruth Marlene', 'É show de bola'),
  bar.music.create('Ruth Marlene *', 'COISINHA SEXY')
]);
bar.art.create('S', [
  bar.music.create('Sabrina', 'DANÇA COMIGO (FESTIVAL)'),
  bar.music.create('Sandy', 'Nunca mais digo adeus'),
  bar.music.create('Sandy e júnior', 'A lenda'),
  bar.music.create('Santa Maria', 'Quero -te mais'),
  bar.music.create('Santa Maria', 'Falésia do amor'),
  bar.music.create('Santamaria', 'Eu sei tu és'),
  bar.music.create('Santamaria', 'Quero tudo (e muito mais)'),
  bar.music.create('Santamaria', 'O coração não chora'),
  bar.music.create('Santamaria', 'Já não da para esperar'),
  bar.music.create('Santamaria', 'tropicalia'),
  bar.music.create('Santamaria', 'vou entrar no teu olhar'),
  bar.music.create('Santamaria', 'Desejo azul'),
  bar.music.create('Santamaria', 'a voar'),
  bar.music.create('Santamaria', 'não da pra viver sem ti'),
  bar.music.create('Santamaria', 'tudo para te amar'),
  bar.music.create('Santamaria', 'QUERO-TE MAIS'),
  bar.music.create('Santamaria', 'QUERO TUDO'),
  bar.music.create('Santamaria', 'O CORAÇÃO NÃO CHORA'),
  bar.music.create('Santamaria', 'VOU ENTRAR NO TEU OLHAR'),
  bar.music.create('Santamaria', 'DESEJO AZUL'),
  bar.music.create('Santamaria', 'SINTO NO AR O TEU OLHAR'),
  bar.music.create('Santamaria', 'TROPICALIA CALIENTE'),
  bar.music.create('Santamaria', 'BOOGIE WOOGIE'),
  bar.music.create('Santamaria', 'VOAR (EM TI)'),
  bar.music.create('Santamaria', 'TUDO PRA TE AMAR'),
  bar.music.create('Santamaria', 'QUERO SER'),
  bar.music.create('Santamaria', 'CASTELOS NA AREIA'),
  bar.music.create('Santamaria', 'NÃO DÁ PRA VIVER SEM TI'),
  bar.music.create('Santamaria', 'TU ÉS O QUE EU + QUERO'),
  bar.music.create('Santamaria', 'JÁ NÃO TENS NADA A VER'),
  bar.music.create('Santamaria', 'EU QUERO SABER (SE SOU AMOR OU ILUSÃO)'),
  bar.music.create('Santamaria', 'ÉS DEMAIS'),
  bar.music.create('Santamaria', 'GOSTO DE AMAR'),
  bar.music.create('Santamaria', 'Eu sei, tu és'),
  bar.music.create('Santamaria', 'Dalay-Lama'),
  bar.music.create('Santamaria', 'Tu és o que eu mais quero'),
  bar.music.create('Santamaria', 'Já não tens nada a ver'),
  bar.music.create('Santamaria', 'QUANDO O AMOR CHEGA'),
  bar.music.create('Santamaria', 'Tudo para te amar'),
  bar.music.create('Santos & Pecadores', 'Horas de prazer'),
  bar.music.create('Santos & Pecadores', 'Não voltarei a ser fiel'),
  bar.music.create('Santos & Pecadores', 'Momento final'),
  bar.music.create('Santos & Pecadores', 'Fala-me de Amor'),
  bar.music.create('Santos & Pecadores', 'A BANDA CANTOU'),
  bar.music.create('Santos & Pecadores', 'PARA ALÉM DO CÉU'),
  bar.music.create('Santos & Pecadores', 'Momento final'),
  bar.music.create('Sara Tavares', 'EU SEI'),
  bar.music.create('Sara Tavares', 'Escolhas'),
  bar.music.create('Sara Tavares', 'Wanoaiami'),
  bar.music.create('Sara Tavares', 'VOA BORBOLETA'),
  bar.music.create('Sara Tavares', 'longe do mundo'),
  bar.music.create('Sara Tavares', 'chamar a musica'),
  bar.music.create('Saul', 'O bacalhau quer alho'),
  bar.music.create('Sérgio Godinho', 'Com um brilhozinho'),
  bar.music.create('Sérgio Godinho', 'COM UM BRILHOZINHO'),
  bar.music.create('Sérgio Godinho', 'O PRIMEIRO DIA'),
  bar.music.create('Sérgio Godinho', 'A noite passada'),
  bar.music.create('Sérgio Godinho', 'O Porto aqui tão perto'),
  bar.music.create('Sérgio Godinho', 'O primeiro dia'),
  bar.music.create('Sérgio Godinho & Caetano Veloso', 'Lisboa que amanhece'),
  bar.music.create('Sérgio Godinho', 'O NAMORO'),
  bar.music.create('Sérgio Rossi *', 'EU DAVA TUDO NA VIDA (p\'ra te ter aqui'),
  bar.music.create('Sérgio Rossi', 'Amanhã (vai ser tarde demais)'),
  bar.music.create('Sétima Legião', 'Por quem não esqueci'),
  bar.music.create('Sétima Legião', 'Sete mares'),
  bar.music.create('Sexto Sentido', 'Chuva'),
  bar.music.create('Sexto Sentido', 'Anjos caídos'),
  bar.music.create('Silence 4', 'To give'),
  bar.music.create('Silence 4', 'Little respect'),
  bar.music.create('Silence 4', 'Borrow'),
  bar.music.create('Simone de Oliveira', 'Desfolhada portuguesa'),
  bar.music.create('Simone de Oliveira', 'Sol de Inverno'),
  bar.music.create('Sitiados', 'Vida de marinheiro'),
  bar.music.create('Só hoje - Jota Quest', 'Perigo'),
  bar.music.create('Só p´ra Contrariar', 'quando é amor'),
  bar.music.create('Só p´ra Contrariar', 'Depois do prazer'),
  bar.music.create('Sonho meu - Gal Costa & Maria Bethânia', 'Um dia,um Adeus'),
  bar.music.create('Sheiks', 'Missing you'),
  bar.music.create('Standard', 'Garota de Ipanema'),
  bar.music.create('Super Teen', 'CORAÇÃO DE PAPELÃO'),
  bar.music.create('Susana Félix', 'Um lugar encantado'),
  bar.music.create('Susana Félix', 'Mais olhos que barriga'),
  bar.music.create('Swing Brasil', 'NA MANTEIGA'),
  bar.music.create('Swing Brasil', 'Maionese')
]);
bar.art.create('T', [
  bar.music.create('Taity', 'Cuidado com a fruta'),
  bar.music.create('Tambor', 'Lisboa p\'ra trás'),
  bar.music.create('tato', 'xote dos milagres'),
  bar.music.create('Táxi', 'Chiclete'),
  bar.music.create('Táxi', 'CAIRO'),
  bar.music.create('Táxi', 'Chiclete'),
  bar.music.create('Tayti', 'Dá-me choque'),
  bar.music.create('Tayti', 'Que calor'),
  bar.music.create('Tayti', 'maos ao ar'),
  bar.music.create('Tayti', 'TEU JOGO DE CINTURA'),
  bar.music.create('Tayti', 'DÁ-ME UM XOXO'),
  bar.music.create('Tayti', 'QUENTE OU FRIO'),
  bar.music.create('Tayti', 'CUIDADO COM A FRUTA'),
  bar.music.create('Tayti', 'PÕE-TE A PAU (Meu Amor)'),
  bar.music.create('Tayti', 'Quente ou frio'),
  bar.music.create('Tédio - Biquini Cavadão', 'Nada Sei(Apnéia'),
  bar.music.create('teixeirinha', 'rei do baralho'),
  bar.music.create('Terrasamba', 'Liberar Geral'),
  bar.music.create('Tetê Espíndola', 'Escrito nas Estrelas'),
  bar.music.create('Tiago Bettencourt', 'CANÇÃO SIMPLES'),
  bar.music.create('Tim e Mariza', 'FADO DO ENCONTRO'),
  bar.music.create('Tim Maia', 'Gostava Tanto de Você'),
  bar.music.create('Tom Jobim', 'Águas de Março'),
  bar.music.create('Tonicha', 'Zumba na caneca'),
  bar.music.create('Tonicha', 'ZUMBA NA CANECA'),
  bar.music.create('Tonicha', 'SERICOTALHO, BACALHAU, AZEITE E ALHO'),
  bar.music.create('Tonicha', 'Menina do altda serra'),
  bar.music.create('Tony carreira', 'Dois corações sozinhos'),
  bar.music.create('Tony carreira', 'Ai destina'),
  bar.music.create('Tony carreira', 'Dois corações sozinhos'),
  bar.music.create('Tony carreira', 'Carinha laroca'),
  bar.music.create('Tony carreira', 'Sabes onde eu estou'),
  bar.music.create('Tony carreira', 'Dois corações sozinhos'),
  bar.music.create('Tony carreira', 'Quando eras minha'),
  bar.music.create('Tony carreira', 'A sonhar contigo'),
  bar.music.create('Tony carreira', 'Cantor de sonhos'),
  bar.music.create('Tony carreira', 'dois coraçoes sozinhos'),
  bar.music.create('Tony carreira', 'CARINHA LAROCA'),
  bar.music.create('Tony carreira', 'QUANDO ERAS MINHA'),
  bar.music.create('Tony carreira', 'A SONHAR CONTIGO'),
  bar.music.create('Tony carreira', 'CANTOR DE SONHOS'),
  bar.music.create('Tony carreira', 'SONHADOR, SONHADOR'),
  bar.music.create('Tony carreira', 'AI DESTINO'),
  bar.music.create('Tony carreira', 'ERAS TU (A METADE DE MIM)'),
  bar.music.create('Tony carreira', 'SE ACORDO E TU NÃO ESTÁS'),
  bar.music.create('Tony carreira', 'QUEM ESQUECEU NÃO CHORA'),
  bar.music.create('Tony carreira', 'DOIS CORAÇÕES SOZINHOS'),
  bar.music.create('Tony carreira', 'DEPOIS DE TI (MAIS NADA)'),
  bar.music.create('Tony carreira', 'MINHA VELHA GUITARRA'),
  bar.music.create('Tony carreira', 'MEU HERÓI PEQUENO'),
  bar.music.create('Tony carreira', 'CARINHA LAROCA'),
  bar.music.create('Tony carreira', 'DOIS CORAÇÕES SOZINHOS'),
  bar.music.create('Tony carreira', 'A sonhar contigo'),
  bar.music.create('Tony carreira', 'Sabes onde eu estou'),
  bar.music.create('Tony carreira', 'O que eu gosto numa mulher'),
  bar.music.create('Tony carreira', 'Sonho de menino'),
  bar.music.create('Tony carreira', 'Sabes onde estou'),
  bar.music.create('Tony carreira', 'VAGABUNDO POR AMOR'),
  bar.music.create('Tony carreira', 'ADEUS ATÉ UM DIA'),
  bar.music.create('Tony carreira', 'NÃO DESISTO DE TI'),
  bar.music.create('Tony carreira', 'O Q. GOSTO NUMA MULHER'),
  bar.music.create('Tony carreira', 'QUEM ERA EU SEM TI'),
  bar.music.create('Tony carreira', 'O QUE VAI SER DE MIM'),
  bar.music.create('Tony carreira', 'ESTE SABOR A TI'),
  bar.music.create('Tony carreira', 'SE ELA PERGUNTAR POR MIM'),
  bar.music.create('Tony carreira', 'A VIDA QUE EU ESCOLHI'),
  bar.music.create('Tony carreira', 'SEM DIZER ADEUS'),
  bar.music.create('Tony carreira', 'MESMO QUE SEJA MENTIRA'),
  bar.music.create('Tony carreira', 'TU LEVASTE A MINHA VIDA'),
  bar.music.create('Tony carreira', 'CORAÇÃO PERDIDO'),
  bar.music.create('Tony carreira', 'EU QUERO NANANA'),
  bar.music.create('Tony carreira', 'SERÁ QUE SOU FELIZ'),
  bar.music.create('Tony carreira', 'TUDO EM MIM'),
  bar.music.create('Tony carreira', 'FALA-LHE DE MIM'),
  bar.music.create('Tony carreira', 'ESTA FALTA DE TI'),
  bar.music.create('Tony carreira', 'BOQUITA LINDA'),
  bar.music.create('Tony carreira', 'ETERNO VAGABUNDO'),
  bar.music.create('Tony carreira', 'TRATA BEM DELA'),
  bar.music.create('Tony carreira', 'MORENA BONITA'),
  bar.music.create('Tony carreira', 'A ESTRADA E EU'),
  bar.music.create('Tony carreira', 'A MINHA GUITARRA'),
  bar.music.create('Tony carreira', 'NÃO HÁ MAIS NINGUÉM'),
  bar.music.create('Tony carreira', 'Depois de ti (mais nada)'),
  bar.music.create('Tony carreira', 'Se acordo e tu não estás'),
  bar.music.create('Tony carreira', 'ESTA FALTA DE TI'),
  bar.music.create('Tony carreira', 'AI DESTINO'),
  bar.music.create('Tony carreira', 'Mãe querida'),
  bar.music.create('Tony carreira', 'Cantor de sonhos'),
  bar.music.create('Tony carreira', 'Sonhador, sonhador'),
  bar.music.create('Tony carreira', 'Meu herói pequeno'),
  bar.music.create('Tony carreira', 'Vagabundo por amor'),
  bar.music.create('Tony carreira', 'Adeus até um dia'),
  bar.music.create('Tony carreira', 'Quem era eu sem ti'),
  bar.music.create('Tony carreira', 'É melhor (dizer adeus)'),
  bar.music.create('Tony carreira', 'Não desisto de ti'),
  bar.music.create('Tony de Matos', 'Cartas de amor'),
  bar.music.create('Tony de Matos', 'O destino marca a hora'),
  bar.music.create('Toquinho / vinicius de moraes', 'tarde em itapua'),
  bar.music.create('Toranja', 'Dá-me ar'),
  bar.music.create('Toranja', 'LAÇOS'),
  bar.music.create('Toranja', 'Cenário'),
  bar.music.create('Toranja', 'A carta'),
  bar.music.create('Toto Cotugno', 'L\'Italiano'),
  bar.music.create('Toto Cutugno', 'L\'ITALIANO'),
  bar.music.create('Toy', 'ÉS TÃO SENSUAL'),
  bar.music.create('Toy', 'Quem é que nunca amou'),
  bar.music.create('Toy', 'archa do Vitória de Setúbal'),
  bar.music.create('Toy', 'CHAMA O ANTÓNIO'),
  bar.music.create('Toy', 'Olhos de água'),
  bar.music.create('Toy', 'Estupidamente apaixonado'),
  bar.music.create('Toy', 'SADO MASOQUISMO'),
  bar.music.create('Toy', 'É só sexo'),
  bar.music.create('Toy', 'Profunda intimidade'),
  bar.music.create('Tradicional', 'Tia anica'),
  bar.music.create('Tradicional', 'Ó tempo volta para trás'),
  bar.music.create('Tradicional', 'O rama o que linda rama'),
  bar.music.create('Tradicional', 'O rosa arredonda a saia'),
  bar.music.create('Tradicional', 'Tudo isto é fado'),
  bar.music.create('Tradicional', 'Apita o comboio'),
  bar.music.create('Tradicional', 'Joana come a papa'),
  bar.music.create('Tradicional', 'Pezinho da vila'),
  bar.music.create('Tradicional', 'Oliveirinha da serra'),
  bar.music.create('Tradicional', 'Olhos castanhos'),
  bar.music.create('Tradicional', 'Coimbra'),
  bar.music.create('Tradicional', 'Alecrim aos molhos'),
  bar.music.create('Tradicional', 'Pezinho da vila'),
  bar.music.create('Tradicional', 'Ao passar a ribeirinha'),
  bar.music.create('Tradicional', 'Mulher gorda'),
  bar.music.create('Tradicional', 'Laurindinha'),
  bar.music.create('Tradicional', 'Malhão'),
  bar.music.create('Tradicional', 'Marcha cheira a Lisboa'),
  bar.music.create('Tradicional', 'Ao passar a ribeirinha'),
  bar.music.create('Tradicional', 'Ouvi um passarinho'),
  bar.music.create('Tradicional', 'Alecrim aos molhos'),
  bar.music.create('Tradicional', 'toca o sino'),
  bar.music.create('Tres Tristes tigres', 'O mundo a meus pés'),
  bar.music.create('Tres Tristes tigres', 'ZAP CANAL'),
  bar.music.create('Tribalistas', 'Velha infância'),
  bar.music.create('Tribalistas', 'já sei namorar'),
  bar.music.create('Trio Odemira', 'ANEL DE NOIVADO'),
  bar.music.create('Tristão da Silva', 'Nem às paredes confesso'),
  bar.music.create('Tropical Band', 'MEIA NOITE'),
  bar.music.create('Tó & Junior', 'Porque és tu'),
  bar.music.create('Trovante', 'Saudade'),
  bar.music.create('Trovante', 'Memorias de um beijo'),
  bar.music.create('Trovante', '25 Azul'),
  bar.music.create('Trovante', 'BALADA DAS SETE SAIAS'),
  bar.music.create('Trovante', 'perdidamenrte')
]);
bar.art.create('U', [
  bar.music.create('UHF', 'Menina estas e janela'),
  bar.music.create('UHF', 'CAVALOS DE CORRIDA'),
  bar.music.create('UHF', 'RUA DO CARMO'),
  bar.music.create('UHF', 'UMA PALAVRA TUA'),
  bar.music.create('UHF', 'Matas-me com o teu olhar'),
  bar.music.create('UHF', 'Quando a alegria for para todos'),
  bar.music.create('UHF', 'Rua do Carmo'),
  bar.music.create('UHF', 'Cavalos de corrida'),
  bar.music.create('UHF', 'Matas-me com o teu olhar'),
  bar.music.create('UHF', 'Rua do Carmo'),
  bar.music.create('UHF', 'Foge comigo Maria'),
  bar.music.create('UHF', 'Sou Benfica')
]);
bar.art.create('V', [
  bar.music.create('Vado kizomba', 'fazi amor cu bo'),
  bar.music.create('Valentino', 'ÉS MAIS QUE UM AMOR'),
  bar.music.create('Vários Artistas', 'Mãe querida, mãe querida'),
  bar.music.create('Vitor Espadinha', 'Recordar e viver'),
  bar.music.create('Vitorino', 'Menina estás à janela'),
  bar.music.create('Vitorino & Septeto Habanero', 'Desde el dia en que te vi'),
  bar.music.create('Vitorino', 'A queda do império'),
  bar.music.create('Viviane', 'A vida não chega')
]);
bar.art.create('W-X', [
  bar.music.create('Wando', 'FOGO E PAIXÃO'),
  bar.music.create('Xutos & Pontapés', 'PRA TI MARIA'),
  bar.music.create('Xutos & Pontapés', 'O HOMEM DO LEME'),
  bar.music.create('Xutos & Pontapés', 'CHUVA DISSOLVENTE'),
  bar.music.create('Xutos & Pontapés', 'Fim do mês'),
  bar.music.create('Xutos & Pontapés', 'Ai se ele cai'),
  bar.music.create('Xutos & Pontapés', 'Circo de feras'),
  bar.music.create('Xutos & Pontapés', 'Não sou o único'),
  bar.music.create('Xutos & Pontapés', 'Circo de feras'),
  bar.music.create('Xutos & Pontapés', 'Homem do leme (versão " Ao Vivo'),
  bar.music.create('Xutos & Pontapés', 'Chuva Dissolvente'),
  bar.music.create('Xutos & Pontapés', 'A minha casinha'),
  bar.music.create('Xutos & Pontapés', 'À minha maneira'),
  bar.music.create('Xutos & Pontapés', 'Contentores'),
  bar.music.create('Xutos & Pontapés', 'Fim do mês'),
  bar.music.create('Xutos & Pontapés', 'Para ti Maria'),
  bar.music.create('Xutos & Pontapés', 'Vida Malvada'),
  bar.music.create('Xutos & Pontapés', 'O mundo ao contrário'),
  bar.music.create('Xutos & Pontapés', 'P\'ra sempre'),
  bar.music.create('Xutos & Pontapés', 'BARCOS GREGOS'),
  bar.music.create('Xutos & Pontapés', 'SOMBRA COLORIDA'),
  bar.music.create('Xutos & Pontapés', 'DÁ UM MERGULHO'),
  bar.music.create('Xutos & Pontapés', 'MANHÃ SUBMERSA')
]);
bar.art.create('Z', [
  bar.music.create('Zé Cabra', 'São lágrimas, são lágrimas'),
  bar.music.create('Zé Cabra', 'Deixei tudo por ela'),
  bar.music.create('ze dantas/luiz gonzaga', 'o xote das meninas'),
  bar.music.create('Zé de Camargo e Luciano', 'E o amor'),
  bar.music.create('Zé Praia', 'VELHA CARRINHA'),
  bar.music.create('Zeca Afonso', 'Venham mais cinco'),
  bar.music.create('zelia duncan', 'catedral'),
  bar.music.create('zeze di camargo e luciano', 'eu te amo'),
  bar.music.create('zeze di camargo e luciano', 'sufocado'),
  bar.music.create('Zizi Possi', 'Homem com H')
]);
  bar.art.setItems('Recomendado', [
  bar.music.get(1000),
  bar.music.get(117),
  bar.music.get(1301),
  bar.music.get(204),
  bar.music.get(207),
  bar.music.get(303),
  bar.music.get(310),
  bar.music.get(403),
  bar.music.get(501),
  bar.music.get(712),
  bar.music.get(810),
  bar.music.get(811),
  bar.music.get(901),
  bar.music.get(1010),
  bar.music.get(1110),
  bar.music.get(1400),
  bar.music.get(1504),
  bar.music.get(1707),
  bar.music.get(2012),
  bar.music.get(2102),
  bar.music.get(2103),
  bar.music.get(2212),
  bar.music.get(2306),
  bar.music.get(2801)
]);
